import { family as f, question as q } from "../common.mjs";

export const characters = [
  q("Name a movie villain people love to hate.", [
    f("Darth Vader", ["vader", "lord vader", "anakin skywalker"]),
    f("The Joker", ["joker", "the clown prince of crime", "joker from batman"]),
    f("Hannibal Lecter", ["dr lecter", "hannibal the cannibal", "lecter"]),
    f("Voldemort", ["lord voldemort", "he who must not be named", "tom riddle"]),
    f("Thanos", ["the mad titan", "mad titan", "thanos from avengers"]),
    f("Scar", ["scar from the lion king", "uncle scar", "simba's uncle"]),
    f("Hans Gruber", ["gruber", "die hard villain", "alan rickman in die hard"]),
    f("Freddy Krueger", ["freddy", "krueger", "nightmare on elm street killer"]),
    f("Michael Myers", ["myers", "the shape", "halloween killer"]),
    f("Norman Bates", ["bates", "psycho killer", "bates motel owner"]),
    f("Anton Chigurh", ["chigurh", "no country for old men killer", "coin flip killer"]),
    f("Agent Smith", ["smith from the matrix", "mr smith", "matrix agent"]),
    f("Cruella de Vil", ["cruella", "101 dalmatians villain", "dalmatian villain"]),
    f("Sauron", ["the dark lord sauron", "eye of sauron", "lord of the rings dark lord"]),
    f("Nurse Ratched", ["ratched", "mildred ratched", "cuckoo's nest nurse"]),
    f("Loki", ["loki laufeyson", "god of mischief", "thor's brother"]),
  ]),
  q("Name a movie hero who feels like an ordinary person.", [
    f("John McClane", ["mcclane", "die hard hero", "john mcclane from die hard"]),
    f("Rocky Balboa", ["rocky", "the italian stallion", "balboa"]),
    f("Marty McFly", ["marty", "mcfly", "back to the future hero"]),
    f("Forrest Gump", ["forrest", "gump", "run forrest run"]),
    f("Peter Parker", ["spider-man", "spiderman", "the friendly neighbourhood spider-man"]),
    f("Frodo Baggins", ["frodo", "baggins", "ring bearer"]),
    f("Katniss Everdeen", ["katniss", "the girl on fire", "hunger games heroine"]),
    f("Ellen Ripley", ["ripley", "lieutenant ripley", "alien survivor"]),
    f("Andy Dufresne", ["dufresne", "shawshank prisoner", "andy from shawshank"]),
    f("Sarah Connor", ["connor", "mother of john connor", "john connor's mum"]),
    f("Neo", ["thomas anderson", "the one", "matrix hero"]),
    f("Harry Potter", ["harry", "the boy who lived", "potter"]),
    f("Luke Skywalker", ["luke", "skywalker", "farm boy from tatooine"]),
    f("Erin Brockovich", ["erin", "brockovich", "erin brockovich the film"]),
    f("Mark Watney", ["watney", "the martian", "stranded botanist"]),
    f("Bilbo Baggins", ["bilbo", "the hobbit hero", "burglar"]),
  ]),
  q("Name a movie sidekick you'd want on your team.", [
    f("Samwise Gamgee", ["sam", "samwise", "sam gamgee"]),
    f("Chewbacca", ["chewie", "wookiee", "han solo's co-pilot"]),
    f("Donkey", ["donkey from shrek", "shrek's donkey", "talking donkey"]),
    f("R2-D2", ["r2d2", "artoo", "astromech droid"]),
    f("C-3PO", ["c3po", "threepio", "protocol droid"]),
    f("Genie", ["the genie", "aladdin's genie", "robin williams genie"]),
    f("Ron Weasley", ["ron", "weasley", "harry's best friend ron"]),
    f("Hermione Granger", ["hermione", "granger", "harry's friend hermione"]),
    f("Dory", ["dory the fish", "just keep swimming fish", "nemo's blue friend"]),
    f("Timon and Pumbaa", ["timon", "pumbaa", "hakuna matata pair"]),
    f("Groot", ["baby groot", "i am groot", "guardians tree"]),
    f("Rocket Raccoon", ["rocket", "raccoon from guardians", "guardians raccoon"]),
    f("Baymax", ["baymax the robot", "big hero 6 robot", "inflatable healthcare companion"]),
    f("Mushu", ["mushu the dragon", "mulan's dragon", "eddie murphy dragon"]),
    f("Robin", ["batman's sidekick", "boy wonder", "dick grayson"]),
    f("Olaf", ["olaf the snowman", "frozen snowman", "warm hugs snowman"]),
  ]),
  q("Name a movie character with an unforgettable line.", [
    f("The Terminator", ["terminator", "t-800", "arnold's terminator"]),
    f("James Bond", ["bond", "007", "agent 007"]),
    f("Buzz Lightyear", ["buzz", "to infinity and beyond guy", "space ranger buzz"]),
    f("Gandalf", ["gandalf the grey", "gandalf the white", "you shall not pass wizard"]),
    f("E.T.", ["et", "the extra-terrestrial", "phone home alien"]),
    f("Forrest Gump", ["forrest", "gump", "box of chocolates guy"]),
    f("Darth Vader", ["vader", "lord vader", "i am your father"]),
    f("Yoda", ["master yoda", "do or do not", "small green jedi"]),
    f("Gollum", ["smeagol", "my precious creature", "sméagol"]),
    f("Dirty Harry", ["harry callahan", "callahan", "do you feel lucky punk"]),
    f("Don Corleone", ["vito corleone", "the godfather", "offer he can't refuse"]),
    f("Maximus", ["maximus decimus meridius", "gladiator hero", "are you not entertained"]),
    f("Jack Sparrow", ["captain jack sparrow", "captain sparrow", "savvy pirate"]),
    f("Dorothy Gale", ["dorothy", "no place like home girl", "wizard of oz dorothy"]),
    f("Jules Winnfield", ["jules", "pulp fiction hitman", "ezekiel 25:17 guy"]),
    f("Hal 9000", ["hal", "hal-9000", "i'm sorry dave computer"]),
  ]),
  q("Name a talking animal from a movie.", [
    f("Simba", ["simba the lion", "lion king cub", "young simba"]),
    f("Nemo", ["nemo the clownfish", "finding nemo fish", "marlin's son"]),
    f("Dory", ["dory the fish", "blue tang", "forgetful fish"]),
    f("Donkey", ["donkey from shrek", "shrek's donkey", "talking donkey"]),
    f("Baloo", ["baloo the bear", "jungle book bear", "bare necessities bear"]),
    f("Bambi", ["bambi the deer", "young deer", "disney fawn"]),
    f("Remy", ["remy the rat", "ratatouille rat", "chef rat"]),
    f("Timon", ["timon the meerkat", "lion king meerkat", "meerkat"]),
    f("Pumbaa", ["pumbaa the warthog", "lion king warthog", "warthog"]),
    f("Babe", ["babe the pig", "sheep pig", "talking pig"]),
    f("Nala", ["nala the lioness", "simba's friend nala", "lion king lioness"]),
    f("Toothless", ["toothless the dragon", "night fury", "how to train your dragon dragon"]),
    f("Po", ["po the panda", "dragon warrior", "kung fu panda"]),
    f("Mushu", ["mushu the dragon", "mulan's dragon", "small red dragon"]),
    f("Scar", ["uncle scar", "scar the lion", "lion king villain"]),
    f("Marlin", ["marlin the clownfish", "nemo's dad", "nemo's father"]),
  ]),
  q("Name a movie character who would ace a heist.", [
    f("Danny Ocean", ["danny", "ocean", "george clooney's ocean"]),
    f("Ethan Hunt", ["hunt", "mission impossible agent", "imf agent hunt"]),
    f("Neil McCauley", ["mccauley", "heat robber", "robert de niro in heat"]),
    f("Dominic Toretto", ["dom", "toretto", "dom toretto"]),
    f("Keyser Soze", ["keyser söze", "soze", "usual suspects mastermind"]),
    f("The Joker", ["joker", "clown prince of crime", "joker from the dark knight"]),
    f("Selina Kyle", ["catwoman", "cat woman", "the cat burglar"]),
    f("Han Solo", ["han", "solo", "smuggler han"]),
    f("Jack Sparrow", ["captain jack sparrow", "captain sparrow", "pirate jack"]),
    f("Thomas Crown", ["the thomas crown affair", "crown", "crown affair thief"]),
    f("Arsène Lupin", ["arsene lupin", "lupin", "gentleman thief"]),
    f("Gru", ["felonius gru", "gru from despicable me", "the moon thief"]),
    f("Baby", ["baby driver", "the getaway driver baby", "baby from baby driver"]),
    f("Bruce Wayne", ["batman", "the dark knight", "bruce wayne batman"]),
    f("Robin Hood", ["robin of locksley", "prince of thieves", "outlaw of sherwood"]),
    f("Rusty Ryan", ["rusty", "ryan from ocean's eleven", "brad pitt's ocean's character"]),
  ]),
];
