import { family as f, question as q } from "../common.mjs";

export const craft = [
  q("Name something that makes a movie scene scary.", [
    f("Music", ["creepy score", "eerie soundtrack", "tense music"]),
    f("Darkness", ["dark rooms", "no lights", "low lighting"]),
    f("Silence", ["sudden quiet", "dead silence", "quiet before the scare"]),
    f("Jump scares", ["jump scare", "sudden shock", "something leaping out"]),
    f("Shadows", ["moving shadows", "shadowy figures", "things in the shadows"]),
    f("Sound effects", ["creaking doors", "strange noises", "scary sound design"]),
    f("Not seeing the monster", ["unseen threat", "hidden monster", "what you can't see"]),
    f("A creepy child", ["scary kids", "spooky child", "eerie kid"]),
    f("Fog", ["mist", "thick fog", "foggy woods"]),
    f("Isolation", ["being alone", "remote location", "cabin in the woods"]),
    f("A slow build", ["slow pacing", "building tension", "creeping dread"]),
    f("Whispering", ["whispers", "hushed voices", "creepy whispers"]),
    f("Flickering lights", ["lights going out", "flashing bulbs", "flickering bulbs"]),
    f("Mirrors", ["mirror reflections", "reflection scares", "something in the mirror"]),
    f("Masks", ["scary masks", "masked figure", "creepy mask"]),
    f("Clowns", ["creepy clown", "scary clowns", "evil clown"]),
  ]),
  q("Name a job on a film set.", [
    f("Director", ["film director", "the director", "movie director"]),
    f("Actor", ["actress", "cast member", "performer"]),
    f("Producer", ["film producer", "movie producer", "executive producer"]),
    f("Cinematographer", ["director of photography", "dp", "camera operator"]),
    f("Editor", ["film editor", "video editor", "movie editor"]),
    f("Screenwriter", ["writer", "script writer", "scriptwriter"]),
    f("Sound designer", ["sound engineer", "sound mixer", "foley artist"]),
    f("Costume designer", ["wardrobe", "costume department", "wardrobe designer"]),
    f("Makeup artist", ["make-up artist", "hair and makeup", "makeup department"]),
    f("Stunt performer", ["stuntman", "stunt double", "stunt coordinator"]),
    f("Gaffer", ["chief lighting technician", "lighting chief", "head electrician"]),
    f("Set designer", ["production designer", "set decorator", "art director"]),
    f("Composer", ["film composer", "score composer", "music composer"]),
    f("Best boy", ["best boy electric", "gaffer's assistant", "assistant gaffer"]),
    f("Grip", ["key grip", "dolly grip", "grip crew"]),
    f("Script supervisor", ["continuity", "continuity supervisor", "script continuity"]),
  ]),
  q("Name a classic movie special effects technique.", [
    f("CGI", ["computer generated imagery", "computer graphics", "computer effects"]),
    f("Practical effects", ["practical fx", "real effects", "in-camera effects"]),
    f("Green screen", ["greenscreen", "chroma key", "blue screen"]),
    f("Miniatures", ["scale models", "model shots", "miniature effects"]),
    f("Stop motion", ["stop-motion", "claymation", "frame by frame animation"]),
    f("Motion capture", ["mocap", "performance capture", "mo-cap"]),
    f("Animatronics", ["animatronic puppets", "robotic puppets", "mechanical creatures"]),
    f("Matte painting", ["matte paintings", "painted backdrops", "painted backgrounds"]),
    f("Prosthetic makeup", ["prosthetics", "special makeup", "creature makeup"]),
    f("Rear projection", ["back projection", "process shot", "projected backdrops"]),
    f("Wire work", ["wirework", "wire fu", "harness flying"]),
    f("Puppetry", ["puppets", "muppet-style effects", "puppeteering"]),
    f("Forced perspective", ["perspective trick", "size illusion", "camera perspective trick"]),
    f("Slow motion", ["slow-mo", "slo-mo", "high speed photography"]),
    f("Bullet time", ["bullet-time", "matrix effect", "frozen time shot"]),
    f("Squibs", ["blood squibs", "bullet hit effects", "exploding blood packs"]),
  ]),
  q("Name a type of camera shot or camera move.", [
    f("Close-up", ["close up", "closeup", "tight shot"]),
    f("Tracking shot", ["follow shot", "dolly shot", "tracking move"]),
    f("Dolly zoom", ["vertigo effect", "zolly", "contra zoom"]),
    f("Wide shot", ["long shot", "wide angle", "establishing wide"]),
    f("Aerial shot", ["drone shot", "bird's eye shot", "helicopter shot"]),
    f("Long take", ["one-shot", "single take", "oner"]),
    f("Slow motion", ["slow-mo", "slo-mo", "slow mo shot"]),
    f("Point of view", ["pov shot", "pov", "first person shot"]),
    f("Crane shot", ["crane move", "jib shot", "crane"]),
    f("Handheld", ["shaky cam", "handheld camera", "handheld shot"]),
    f("Pan", ["panning shot", "pan shot", "camera pan"]),
    f("Over-the-shoulder", ["over the shoulder", "ots shot", "over the shoulder shot"]),
    f("Steadicam", ["steady cam", "steadicam shot", "gimbal shot"]),
    f("Zoom", ["zoom in", "zoom shot", "crash zoom"]),
    f("Establishing shot", ["scene setter", "location shot", "opening wide shot"]),
    f("Dutch angle", ["dutch tilt", "tilted camera", "canted angle"]),
  ]),
  q("Name something a movie trailer does to hook you.", [
    f("Music", ["epic score", "big soundtrack", "dramatic music"]),
    f("Voiceover", ["narration", "in a world voice", "deep voice narration"]),
    f("Quick cuts", ["fast editing", "rapid cuts", "montage"]),
    f("Big explosion", ["explosions", "action shots", "blowing things up"]),
    f("A famous star", ["big names", "star cast", "famous faces"]),
    f("A twist tease", ["teasing a twist", "mystery hook", "cliffhanger"]),
    f("The best jokes", ["comedy moments", "funniest lines", "big laughs"]),
    f("A countdown", ["release date", "coming soon card", "date reveal"]),
    f("Slow reveal", ["gradual reveal", "teasing the monster", "hiding the creature"]),
    f("A big bass drop", ["braam", "big sound hit", "loud sound hit"]),
    f("A recognizable song", ["famous song", "cover song", "popular track"]),
    f("A tagline", ["catchphrase", "slogan", "one-liner"]),
    f("Silence then a drop", ["quiet then loud", "pause before the action", "sudden silence"]),
    f("Dialogue snippets", ["memorable line", "quotable lines", "one line of dialogue"]),
    f("A shocking moment", ["big surprise", "gasp moment", "shock scene"]),
    f("Sweeping landscapes", ["epic scenery", "aerial landscapes", "beautiful vistas"]),
  ]),
  q("Name a famous piece of movie music or a movie sound.", [
    f("The Jaws theme", ["jaws music", "da dum da dum", "shark theme"]),
    f("The Imperial March", ["darth vader's theme", "vader's theme", "star wars imperial march"]),
    f("The Wilhelm scream", ["wilhelm scream sound", "famous movie scream", "stock scream"]),
    f("The Star Wars main theme", ["star wars fanfare", "star wars opening", "star wars theme music"]),
    f("The Psycho shower strings", ["psycho strings", "screeching violins", "psycho shower music"]),
    f("The Inception horn", ["inception braam", "braaam", "inception bwaaam"]),
    f("The James Bond theme", ["bond theme", "007 theme", "james bond music"]),
    f("The Indiana Jones theme", ["raiders march", "indy theme", "raiders of the lost ark theme"]),
    f("The Jurassic Park theme", ["jurassic park music", "welcome to jurassic park", "jurassic theme"]),
    f("The Mission: Impossible theme", ["mission impossible theme", "mi theme", "lalo schifrin theme"]),
    f("The Ghostbusters theme", ["who you gonna call", "ghostbusters song", "ghostbusters music"]),
    f("My Heart Will Go On", ["titanic song", "celine dion titanic", "titanic theme song"]),
    f("Gonna Fly Now", ["rocky theme", "rocky music", "rocky training music"]),
    f("The THX Deep Note", ["thx sound", "thx logo sound", "thx deep note"]),
    f("The Lightsaber hum", ["lightsaber sound", "lightsaber noise", "saber hum"]),
    f("The Godfather theme", ["godfather music", "love theme from the godfather", "speak softly love"]),
  ]),
];
