import { family as f, question as q } from "../common.mjs";

export const franchises = [
  q("Name a movie franchise with more sequels than you can count.", [
    f("Fast & Furious", ["fast and furious", "the fast saga", "fast furious"]),
    f("James Bond", ["bond films", "007 films", "the bond series"]),
    f("Marvel Cinematic Universe", ["mcu", "marvel movies", "the avengers series"]),
    f("Star Wars", ["star wars saga", "star wars films", "skywalker saga"]),
    f("Halloween", ["halloween films", "michael myers series", "halloween franchise"]),
    f("Friday the 13th", ["friday the thirteenth", "jason series", "friday 13th films"]),
    f("Saw", ["saw films", "jigsaw series", "saw franchise"]),
    f("Godzilla", ["godzilla films", "monsterverse", "toho godzilla"]),
    f("Harry Potter", ["potter films", "wizarding world films", "harry potter series"]),
    f("Mission: Impossible", ["mission impossible", "mi films", "ethan hunt series"]),
    f("Transformers", ["transformers films", "michael bay transformers", "autobots series"]),
    f("Pirates of the Caribbean", ["pirates films", "jack sparrow series", "pirates franchise"]),
    f("Rocky", ["rocky films", "rocky balboa series", "rocky and creed series"]),
    f("Toy Story", ["toy story films", "woody and buzz series", "toy story franchise"]),
    f("Resident Evil", ["resident evil films", "milla jovovich series", "resident evil franchise"]),
    f("Carry On", ["carry on films", "carry on series", "carry on movies"]),
  ]),
  q("Name a movie franchise you could binge in one weekend.", [
    f("The Lord of the Rings", ["lotr", "lord of the rings trilogy", "middle-earth films"]),
    f("Harry Potter", ["potter films", "wizarding world films", "harry potter series"]),
    f("Star Wars", ["star wars saga", "star wars films", "skywalker saga"]),
    f("The Godfather", ["godfather trilogy", "corleone films", "godfather films"]),
    f("Marvel Cinematic Universe", ["mcu", "marvel movies", "the avengers series"]),
    f("Toy Story", ["toy story films", "woody and buzz series", "toy story franchise"]),
    f("Back to the Future", ["back to the future trilogy", "marty mcfly films", "bttf"]),
    f("Jurassic Park", ["jurassic world", "jurassic films", "jurassic park series"]),
    f("Indiana Jones", ["indy films", "raiders series", "indiana jones series"]),
    f("The Matrix", ["matrix trilogy", "matrix films", "neo series"]),
    f("Pirates of the Caribbean", ["pirates films", "jack sparrow series", "pirates franchise"]),
    f("The Hunger Games", ["hunger games films", "katniss series", "hunger games franchise"]),
    f("Mission: Impossible", ["mission impossible", "mi films", "ethan hunt series"]),
    f("John Wick", ["john wick films", "baba yaga series", "john wick franchise"]),
    f("Rocky", ["rocky films", "rocky balboa series", "rocky and creed series"]),
    f("Twilight", ["twilight saga", "twilight films", "bella and edward series"]),
  ]),
  q("Name an animation studio.", [
    f("Pixar", ["pixar animation studios", "pixar studios", "toy story studio"]),
    f("Disney", ["walt disney animation studios", "disney animation", "walt disney animation"]),
    f("DreamWorks", ["dreamworks animation", "dream works", "shrek studio"]),
    f("Studio Ghibli", ["ghibli", "miyazaki's studio", "spirited away studio"]),
    f("Illumination", ["illumination entertainment", "minions studio", "despicable me studio"]),
    f("Blue Sky Studios", ["blue sky", "ice age studio", "blue sky animation"]),
    f("Aardman", ["aardman animations", "wallace and gromit studio", "shaun the sheep studio"]),
    f("Laika", ["laika studios", "coraline studio", "kubo studio"]),
    f("Sony Pictures Animation", ["sony animation", "spider-verse studio", "sony pictures animation studio"]),
    f("Warner Bros. Animation", ["warner animation", "looney tunes studio", "warner bros animation"]),
    f("Cartoon Saloon", ["cartoon saloon studio", "song of the sea studio", "wolfwalkers studio"]),
    f("Hanna-Barbera", ["hanna barbera", "scooby-doo studio", "flintstones studio"]),
    f("Toei Animation", ["toei", "dragon ball studio", "toei studio"]),
    f("Madhouse", ["madhouse studio", "madhouse animation", "paprika studio"]),
    f("Fleischer Studios", ["fleischer", "betty boop studio", "popeye studio"]),
    f("Nickelodeon Animation", ["nickelodeon animation studio", "spongebob studio", "nickelodeon movies"]),
  ]),
  q("Name a film studio.", [
    f("Warner Bros.", ["warner brothers", "wb", "warner bros pictures"]),
    f("Universal", ["universal pictures", "universal studios", "universal films"]),
    f("Paramount", ["paramount pictures", "paramount studios", "paramount films"]),
    f("Disney", ["walt disney pictures", "walt disney studios", "disney studios"]),
    f("Sony Pictures", ["sony", "columbia pictures", "sony pictures entertainment"]),
    f("20th Century Studios", ["20th century fox", "twentieth century fox", "fox studios"]),
    f("MGM", ["metro-goldwyn-mayer", "metro goldwyn mayer", "mgm studios"]),
    f("Lionsgate", ["lions gate", "lionsgate films", "lionsgate studios"]),
    f("A24", ["a24 films", "a twenty four", "a24 studio"]),
    f("Pixar", ["pixar animation studios", "pixar studios", "toy story studio"]),
    f("Miramax", ["miramax films", "miramax studios", "miramax pictures"]),
    f("DreamWorks", ["dreamworks pictures", "dream works", "dreamworks studios"]),
    f("Netflix", ["netflix films", "netflix studios", "netflix originals"]),
    f("Focus Features", ["focus films", "universal focus"]),
    f("Legendary", ["legendary pictures", "legendary entertainment", "legendary studios"]),
    f("Lucasfilm", ["lucas film", "star wars studio", "lucasfilm ltd"]),
  ]),
  q("Name a sequel widely rated as good as the original.", [
    f("The Empire Strikes Back", ["empire strikes back", "star wars episode v", "star wars v"]),
    f("The Godfather Part II", ["godfather part 2", "godfather 2", "godfather part two"]),
    f("Terminator 2", ["terminator 2 judgment day", "t2", "terminator 2 judgement day"]),
    f("Aliens", ["aliens 1986", "alien sequel", "james cameron's aliens"]),
    f("The Dark Knight", ["dark knight", "batman the dark knight", "nolan's dark knight"]),
    f("Toy Story 2", ["toy story two", "toy story 2 film", "woody's roundup film"]),
    f("Toy Story 3", ["toy story three", "toy story 3 film", "incinerator scene film"]),
    f("The Road Warrior", ["mad max 2", "mad max two", "road warrior film"]),
    f("Spider-Man 2", ["spiderman 2", "spider man 2", "spider-man two"]),
    f("Paddington 2", ["paddington two", "paddington 2 film", "paddington 2 movie"]),
    f("Evil Dead II", ["evil dead 2", "evil dead two", "evil dead ii film"]),
    f("The Wrath of Khan", ["star trek ii", "star trek 2", "wrath of khan"]),
    f("Shrek 2", ["shrek two", "shrek 2 film", "shrek 2 movie"]),
    f("John Wick: Chapter 2", ["john wick 2", "john wick chapter two", "john wick two"]),
    f("Mission: Impossible – Fallout", ["fallout", "mission impossible fallout", "mi fallout"]),
    f("Superman II", ["superman 2", "superman two", "superman ii film"]),
  ]),
  q("Name a movie theme tune everyone recognizes.", [
    f("Star Wars", ["star wars theme", "star wars main title", "the imperial march"]),
    f("James Bond", ["james bond theme", "bond theme", "007 theme"]),
    f("Jaws", ["jaws theme", "da dum da dum", "shark theme"]),
    f("Indiana Jones", ["raiders march", "indiana jones theme", "raiders of the lost ark theme"]),
    f("Mission: Impossible", ["mission impossible theme", "mi theme", "lalo schifrin theme"]),
    f("Harry Potter", ["hedwig's theme", "harry potter theme", "hedwigs theme"]),
    f("Jurassic Park", ["jurassic park theme", "jurassic theme", "welcome to jurassic park"]),
    f("Pirates of the Caribbean", ["he's a pirate", "pirates theme", "hes a pirate"]),
    f("Superman", ["superman theme", "superman march", "john williams superman"]),
    f("The Lord of the Rings", ["shire theme", "lotr theme", "lord of the rings theme"]),
    f("Ghostbusters", ["ghostbusters theme", "who you gonna call", "ray parker jr theme"]),
    f("Rocky", ["gonna fly now", "rocky theme", "rocky's theme"]),
    f("Star Trek", ["star trek theme", "star trek fanfare", "space the final frontier theme"]),
    f("Back to the Future", ["back to the future theme", "bttf theme", "power of love theme"]),
    f("The Godfather", ["godfather theme", "love theme from the godfather", "speak softly love"]),
    f("Halloween", ["halloween theme", "michael myers theme", "john carpenter halloween theme"]),
  ]),
];
