import { family as f, question as q } from "../common.mjs";

export const genres = [
  q("Name a movie genre that never gets old.", [
    f("Comedy", ["funny movies", "comedies", "stand-up comedy film"]),
    f("Action", ["action movies", "action adventure", "shoot-em-up"]),
    f("Horror", ["scary movies", "horror films", "creepy movies"]),
    f("Science fiction", ["sci-fi", "scifi", "space movies"]),
    f("Thriller", ["suspense", "edge-of-your-seat films", "thrillers"]),
    f("Drama", ["dramas", "serious films", "character study"]),
    f("Animation", ["animated films", "cartoons", "animated movies"]),
    f("Romance", ["love stories", "romantic films", "romantic movies"]),
    f("Fantasy", ["fantasy epics", "swords and sorcery", "magical worlds"]),
    f("Crime", ["crime films", "gangster movies", "crime dramas"]),
    f("Adventure", ["adventure films", "quest movies", "swashbuckler"]),
    f("Mystery", ["whodunit", "detective films", "murder mystery"]),
    f("Musical", ["musicals", "song and dance films", "movie musical"]),
    f("Western", ["westerns", "cowboy movies", "wild west films"]),
    f("Documentary", ["documentaries", "nonfiction film", "docs"]),
    f("War film", ["war movies", "combat films", "battlefield drama"]),
  ]),
  q("Name a movie subgenre with its own loyal fanbase.", [
    f("Superhero", ["superhero movies", "comic book movies", "caped crusader films"]),
    f("Slasher", ["slasher films", "stalk and slash", "masked killer movies"]),
    f("Rom-com", ["romantic comedy", "romcom", "romantic comedies"]),
    f("Zombie", ["zombie movies", "undead films", "zombie apocalypse"]),
    f("Heist", ["heist movies", "caper films", "robbery movies"]),
    f("Film noir", ["noir", "classic noir", "black and white crime"]),
    f("Space opera", ["galactic adventure", "space saga", "interstellar epic"]),
    f("Found footage", ["found-footage horror", "shaky cam movies", "handheld horror"]),
    f("Disaster movie", ["disaster films", "catastrophe films", "natural disaster movies"]),
    f("Kung fu", ["martial arts films", "kung fu movies", "chop socky"]),
    f("Spaghetti western", ["italian westerns", "european westerns", "macaroni western"]),
    f("Cyberpunk", ["cyber punk", "neon dystopia", "high tech low life"]),
    f("Buddy cop", ["buddy cop movies", "odd couple cops", "partner cop films"]),
    f("Coming-of-age", ["coming of age films", "teen growing up movies", "youth drama"]),
    f("Body horror", ["body-horror", "flesh horror", "cronenberg style horror"]),
    f("Mockumentary", ["mock documentary", "fake documentary", "faux doc"]),
  ]),
  q("Name a kind of movie worth seeing on the biggest screen you can find.", [
    f("Action blockbuster", ["big action movie", "summer blockbuster", "action spectacle"]),
    f("Sci-fi epic", ["science fiction epic", "space epic", "big sci-fi"]),
    f("Fantasy epic", ["big fantasy", "sword and sorcery epic", "high fantasy film"]),
    f("Superhero movie", ["superhero film", "comic book blockbuster", "hero team-up"]),
    f("Disaster movie", ["disaster film", "catastrophe epic", "end of the world film"]),
    f("War film", ["war epic", "battle movie", "wartime drama"]),
    f("Space adventure", ["space exploration film", "astronaut movie", "outer space movie"]),
    f("Animated feature", ["animated film", "big animation", "pixar-style film"]),
    f("Horror", ["scary movie", "horror film", "cinema scare"]),
    f("Musical", ["movie musical", "big musical", "song and dance spectacle"]),
    f("Nature documentary", ["wildlife film", "planet documentary", "ocean documentary"]),
    f("Western", ["epic western", "cowboy epic", "frontier film"]),
    f("Heist movie", ["heist film", "caper spectacle", "big robbery film"]),
    f("Historical epic", ["period epic", "sword and sandal", "ancient world epic"]),
    f("Concert film", ["music film", "live performance movie", "gig on screen"]),
    f("Racing movie", ["car racing film", "motorsport movie", "driving film"]),
  ]),
  q("Name a genre that fits a rainy Sunday.", [
    f("Comedy", ["comedies", "light comedy", "funny movie"]),
    f("Romance", ["love story", "romantic movie", "romances"]),
    f("Drama", ["dramas", "slow drama", "character drama"]),
    f("Animation", ["animated movie", "cartoons", "animated film"]),
    f("Family film", ["family movie", "kids movie", "family adventure"]),
    f("Mystery", ["whodunit", "detective story", "murder mystery"]),
    f("Fantasy", ["cosy fantasy", "magical adventure", "fairy tale"]),
    f("Documentary", ["documentaries", "nonfiction", "slow documentary"]),
    f("Period drama", ["costume drama", "historical drama", "regency drama"]),
    f("Musical", ["musicals", "feel good musical", "song film"]),
    f("Crime", ["crime film", "detective crime", "crime drama"]),
    f("Adventure", ["adventure film", "quest movie", "journey story"]),
    f("Coming-of-age", ["coming of age", "growing up film", "teen drama"]),
    f("Thriller", ["suspense film", "thrillers", "slow burn thriller"]),
    f("Science fiction", ["sci-fi", "scifi movie", "space story"]),
    f("Sports drama", ["sports movie", "underdog sports film", "athlete story"]),
  ]),
  q("Name a genre that gets parodied a lot.", [
    f("Horror", ["scary movies", "horror films", "slasher spoof"]),
    f("Superhero", ["superhero movies", "hero spoof", "comic book movies"]),
    f("Western", ["cowboy films", "westerns", "wild west spoof"]),
    f("Spy", ["spy films", "secret agent movies", "espionage"]),
    f("Action", ["action movies", "action spoof", "big action films"]),
    f("Science fiction", ["sci-fi", "space movies", "scifi spoof"]),
    f("Disaster movie", ["disaster films", "airplane-style spoof", "catastrophe films"]),
    f("Romance", ["romantic films", "love stories", "rom-com spoof"]),
    f("Kung fu", ["martial arts", "kung fu movies", "chop socky"]),
    f("Gangster", ["mob movies", "mafia films", "gangster films"]),
    f("Fantasy", ["fantasy epics", "swords and sorcery", "medieval fantasy"]),
    f("Sports", ["sports movies", "underdog sports", "sports films"]),
    f("Vampire", ["vampire films", "dracula movies", "bloodsucker movies"]),
    f("Zombie", ["zombie movies", "undead films", "shaun-style zombie"]),
    f("Heist", ["heist films", "caper movies", "robbery movies"]),
    f("War film", ["war movies", "combat films", "military movies"]),
  ]),
  q("Name a genre where the ending matters most.", [
    f("Thriller", ["suspense film", "thrillers", "edge-of-seat film"]),
    f("Mystery", ["whodunit", "detective story", "murder mystery"]),
    f("Horror", ["scary movies", "horror films", "final girl film"]),
    f("Drama", ["dramas", "serious film", "character drama"]),
    f("Heist", ["heist movie", "caper film", "robbery movie"]),
    f("Crime", ["crime film", "crime story", "crime drama"]),
    f("Science fiction", ["sci-fi", "twist sci-fi", "scifi film"]),
    f("Romance", ["love story", "romantic film", "romances"]),
    f("Comedy", ["comedies", "funny movie", "punchline film"]),
    f("Fantasy", ["fantasy epic", "magical story", "quest fantasy"]),
    f("War film", ["war movie", "battle film", "wartime drama"]),
    f("Psychological thriller", ["mind game film", "head trip movie", "twist thriller"]),
    f("Disaster movie", ["disaster film", "survival disaster", "catastrophe film"]),
    f("Slasher", ["slasher film", "stalker horror", "masked killer film"]),
    f("Sports drama", ["underdog film", "sports movie", "big game movie"]),
    f("Western", ["cowboy film", "showdown western", "frontier story"]),
  ]),
];
