import { family as f, question as q } from "../common.mjs";

export const movieNight = [
  q("Name a snack you'd take to the cinema.", [
    f("Popcorn", ["salted popcorn", "sweet popcorn", "buttered popcorn"]),
    f("Nachos", ["nacho chips", "cheesy nachos", "nachos and cheese"]),
    f("Candy", ["sweets", "movie candy", "lollies"]),
    f("Soda", ["fizzy drink", "cola", "soft drink"]),
    f("Hot dog", ["hotdog", "cinema hot dog", "frankfurter"]),
    f("Ice cream", ["ice-cream", "choc ice", "cinema ice cream"]),
    f("Pretzel", ["soft pretzel", "pretzels", "salted pretzel"]),
    f("Chocolate", ["chocolate bar", "chocolate bites", "candy bar"]),
    f("Chips", ["crisps", "potato chips", "tortilla chips"]),
    f("Slushie", ["slush", "frozen drink", "frozen slush"]),
    f("Pizza", ["pizza slice", "cinema pizza", "slice of pizza"]),
    f("Gummy bears", ["gummies", "gummy sweets", "jelly bears"]),
    f("Water", ["bottled water", "water bottle", "a bottle of water"]),
    f("Fries", ["french fries", "cinema fries", "hot fries"]),
    f("Candy floss", ["cotton candy", "fairy floss", "spun sugar"]),
    f("Sour sweets", ["sour candy", "sour belts", "sour lollies"]),
  ]),
  q("Name a movie you can quote from memory.", [
    f("The Lion King", ["lion king", "circle of life film", "simba film"]),
    f("Shrek", ["shrek film", "ogre film", "shrek movie"]),
    f("Monty Python and the Holy Grail", ["holy grail", "monty python", "the holy grail"]),
    f("The Princess Bride", ["princess bride", "inconceivable film", "as you wish film"]),
    f("Star Wars", ["star wars film", "a new hope", "star wars saga"]),
    f("Forrest Gump", ["forrest gump film", "box of chocolates film", "gump"]),
    f("Mean Girls", ["mean girls film", "fetch film", "plastics film"]),
    f("Anchorman", ["anchorman film", "ron burgundy film", "anchorman legend of ron burgundy"]),
    f("The Godfather", ["godfather", "corleone film", "the godfather film"]),
    f("Toy Story", ["toy story film", "woody and buzz film", "to infinity and beyond film"]),
    f("Finding Nemo", ["nemo", "just keep swimming film", "finding nemo film"]),
    f("Home Alone", ["home alone film", "kevin mccallister film", "home alone movie"]),
    f("Dumb and Dumber", ["dumb and dumber film", "lloyd and harry film", "dumb & dumber"]),
    f("Pulp Fiction", ["pulp fiction film", "tarantino pulp fiction", "royale with cheese film"]),
    f("The Big Lebowski", ["big lebowski", "the dude film", "lebowski"]),
    f("Frozen", ["frozen film", "let it go film", "elsa film"]),
  ]),
  q("Name a movie you'd watch at Christmas.", [
    f("Home Alone", ["home alone film", "kevin mccallister film", "home alone movie"]),
    f("Elf", ["elf film", "buddy the elf film", "will ferrell elf"]),
    f("Love Actually", ["love actually film", "richard curtis christmas film", "love actually movie"]),
    f("Die Hard", ["die hard film", "john mcclane christmas film", "die hard movie"]),
    f("The Grinch", ["how the grinch stole christmas", "grinch", "the grinch film"]),
    f("It's a Wonderful Life", ["its a wonderful life", "wonderful life", "george bailey film"]),
    f("Miracle on 34th Street", ["miracle on thirty-fourth street", "miracle on 34th", "santa in court film"]),
    f("The Polar Express", ["polar express", "polar express film", "train to the north pole film"]),
    f("A Christmas Carol", ["christmas carol", "scrooge film", "dickens christmas film"]),
    f("The Nightmare Before Christmas", ["nightmare before christmas", "jack skellington film", "tim burton christmas film"]),
    f("Gremlins", ["gremlins film", "gizmo film", "gremlins movie"]),
    f("Christmas Vacation", ["national lampoon's christmas vacation", "griswold christmas film", "christmas vacation film"]),
    f("The Santa Clause", ["santa clause", "tim allen santa film", "the santa clause film"]),
    f("Arthur Christmas", ["arthur christmas film", "santa's son film", "aardman christmas film"]),
    f("Klaus", ["klaus film", "netflix klaus", "animated santa origin film"]),
    f("Jingle All the Way", ["jingle all the way film", "turbo man film", "arnold christmas film"]),
  ]),
  q("Name a film that made you cry.", [
    f("Titanic", ["titanic film", "jack and rose film", "titanic movie"]),
    f("The Lion King", ["lion king", "mufasa scene film", "simba film"]),
    f("Up", ["up film", "pixar up", "carl and ellie film"]),
    f("Toy Story 3", ["toy story three", "incinerator film", "toy story 3 film"]),
    f("Marley & Me", ["marley and me", "marley and me film", "labrador film"]),
    f("The Notebook", ["notebook", "the notebook film", "noah and allie film"]),
    f("Schindler's List", ["schindlers list", "spielberg holocaust film", "schindler's list film"]),
    f("Forrest Gump", ["forrest gump film", "jenny and forrest film", "gump"]),
    f("Coco", ["coco film", "pixar coco", "remember me film"]),
    f("Bambi", ["bambi film", "bambi's mother film", "disney bambi"]),
    f("Hachi: A Dog's Tale", ["hachi", "hachiko film", "hachi a dogs tale"]),
    f("Inside Out", ["inside out film", "bing bong film", "pixar inside out"]),
    f("The Green Mile", ["green mile", "the green mile film", "john coffey film"]),
    f("The Fault in Our Stars", ["fault in our stars", "the fault in our stars film", "hazel and gus film"]),
    f("Life Is Beautiful", ["life is beautiful film", "la vita e bella", "roberto benigni film"]),
    f("Old Yeller", ["old yeller film", "disney dog film", "old yeller movie"]),
  ]),
  q("Name a movie for a first date.", [
    f("The Notebook", ["notebook", "the notebook film", "noah and allie film"]),
    f("La La Land", ["la la land film", "la la land movie", "ryan gosling musical"]),
    f("Pretty Woman", ["pretty woman film", "julia roberts film", "pretty woman movie"]),
    f("Love Actually", ["love actually film", "christmas romance film", "love actually movie"]),
    f("When Harry Met Sally", ["when harry met sally film", "harry and sally", "billy crystal romance"]),
    f("Notting Hill", ["notting hill film", "hugh grant romance", "notting hill movie"]),
    f("Crazy Rich Asians", ["crazy rich asians film", "crazy rich asians movie", "singapore romcom"]),
    f("Grease", ["grease film", "danny and sandy film", "grease musical"]),
    f("Dirty Dancing", ["dirty dancing film", "baby and johnny film", "dirty dancing movie"]),
    f("Amélie", ["amelie", "amélie film", "amelie film"]),
    f("Before Sunrise", ["before sunrise film", "ethan hawke romance", "vienna romance film"]),
    f("10 Things I Hate About You", ["ten things i hate about you", "10 things", "heath ledger romcom"]),
    f("Casablanca", ["casablanca film", "classic bogart film", "here's looking at you kid film"]),
    f("The Princess Bride", ["princess bride", "as you wish film", "princess bride film"]),
    f("Titanic", ["titanic film", "jack and rose film", "titanic movie"]),
    f("Ratatouille", ["ratatouille film", "pixar ratatouille", "remy film"]),
  ]),
  q("Name a movie that's perfect for a family night.", [
    f("Toy Story", ["toy story film", "woody and buzz film", "toy story movie"]),
    f("Finding Nemo", ["nemo", "finding nemo film", "finding nemo movie"]),
    f("The Lion King", ["lion king", "simba film", "the lion king film"]),
    f("Shrek", ["shrek film", "ogre film", "shrek movie"]),
    f("Frozen", ["frozen film", "elsa film", "frozen movie"]),
    f("Moana", ["moana film", "maui film", "moana movie"]),
    f("The Incredibles", ["incredibles", "the incredibles film", "superhero family film"]),
    f("Coco", ["coco film", "pixar coco", "day of the dead film"]),
    f("Paddington", ["paddington film", "paddington bear film", "paddington movie"]),
    f("Home Alone", ["home alone film", "kevin mccallister film", "home alone movie"]),
    f("Harry Potter", ["harry potter film", "philosopher's stone", "harry potter movie"]),
    f("Back to the Future", ["back to the future film", "marty mcfly film", "delorean film"]),
    f("Mary Poppins", ["mary poppins film", "supercalifragilistic film", "julie andrews film"]),
    f("Despicable Me", ["despicable me film", "minions film", "gru film"]),
    f("Kung Fu Panda", ["kung fu panda film", "po film", "kung fu panda movie"]),
    f("WALL-E", ["wall e", "walle", "wall-e film"]),
  ]),
];
