import { family as f, question as q } from "../common.mjs";

export const stars = [
  q("Name an actor who can carry a movie alone.", [
    f("Tom Hanks", ["hanks", "tom hanks the actor", "forrest gump actor"]),
    f("Tom Cruise", ["cruise", "tom cruise the actor", "mission impossible star"]),
    f("Leonardo DiCaprio", ["dicaprio", "leo dicaprio", "leonardo di caprio"]),
    f("Denzel Washington", ["denzel", "washington", "denzel washington the actor"]),
    f("Brad Pitt", ["pitt", "brad pitt the actor", "fight club actor"]),
    f("Will Smith", ["fresh prince actor", "will smith the actor", "men in black star"]),
    f("Robert De Niro", ["de niro", "deniro", "robert deniro"]),
    f("Keanu Reeves", ["keanu", "reeves", "john wick actor"]),
    f("Harrison Ford", ["ford", "han solo actor", "indiana jones actor"]),
    f("Samuel L. Jackson", ["samuel jackson", "sam jackson", "samuel l jackson"]),
    f("Morgan Freeman", ["freeman", "morgan freeman the actor", "shawshank narrator"]),
    f("Al Pacino", ["pacino", "al pacino the actor", "scarface actor"]),
    f("Jack Nicholson", ["nicholson", "jack nicholson the actor", "the shining actor"]),
    f("Dwayne Johnson", ["the rock", "dwayne the rock johnson", "rock johnson"]),
    f("Johnny Depp", ["depp", "johnny depp the actor", "jack sparrow actor"]),
    f("Meryl Streep", ["streep", "meryl streep the actress", "devil wears prada star"]),
  ]),
  q("Name a film director whose style is instantly recognizable.", [
    f("Quentin Tarantino", ["tarantino", "quentin tarantino the director", "pulp fiction director"]),
    f("Christopher Nolan", ["nolan", "christopher nolan the director", "inception director"]),
    f("Steven Spielberg", ["spielberg", "steven spielberg the director", "jaws director"]),
    f("Wes Anderson", ["anderson", "wes anderson the director", "grand budapest director"]),
    f("Alfred Hitchcock", ["hitchcock", "hitch", "master of suspense"]),
    f("Stanley Kubrick", ["kubrick", "stanley kubrick the director", "2001 director"]),
    f("Martin Scorsese", ["scorsese", "marty scorsese", "goodfellas director"]),
    f("Tim Burton", ["burton", "tim burton the director", "edward scissorhands director"]),
    f("James Cameron", ["james cameron the director", "titanic director"]),
    f("David Lynch", ["lynch", "david lynch the director", "twin peaks creator"]),
    f("Ridley Scott", ["ridley scott the director", "alien director"]),
    f("Guillermo del Toro", ["del toro", "guillermo", "pan's labyrinth director"]),
    f("Denis Villeneuve", ["villeneuve", "denis villeneuve the director", "dune director"]),
    f("Hayao Miyazaki", ["miyazaki", "hayao", "studio ghibli director"]),
    f("The Coen Brothers", ["coen brothers", "joel and ethan coen", "fargo directors"]),
    f("Francis Ford Coppola", ["coppola", "francis coppola", "godfather director"]),
  ]),
  q("Name an actor who has played a superhero.", [
    f("Robert Downey Jr.", ["rdj", "robert downey", "iron man actor"]),
    f("Chris Hemsworth", ["hemsworth", "thor actor", "chris hemsworth the actor"]),
    f("Chris Evans", ["captain america actor", "chris evans the actor", "evans"]),
    f("Hugh Jackman", ["jackman", "wolverine actor", "hugh jackman the actor"]),
    f("Ryan Reynolds", ["reynolds", "deadpool actor", "ryan reynolds the actor"]),
    f("Christian Bale", ["bale", "batman actor bale", "christian bale the actor"]),
    f("Tom Holland", ["holland", "spider-man actor holland", "tom holland the actor"]),
    f("Tobey Maguire", ["maguire", "spider-man actor maguire", "tobey maguire the actor"]),
    f("Scarlett Johansson", ["johansson", "black widow actress", "scarlett johansson the actress"]),
    f("Henry Cavill", ["cavill", "superman actor", "henry cavill the actor"]),
    f("Andrew Garfield", ["garfield", "spider-man actor garfield", "andrew garfield the actor"]),
    f("Ben Affleck", ["affleck", "batman actor affleck", "ben affleck the actor"]),
    f("Gal Gadot", ["gadot", "wonder woman actress", "gal gadot the actress"]),
    f("Chadwick Boseman", ["boseman", "black panther actor", "chadwick boseman the actor"]),
    f("Michael Keaton", ["keaton", "batman actor keaton", "michael keaton the actor"]),
    f("Mark Ruffalo", ["ruffalo", "hulk actor", "mark ruffalo the actor"]),
  ]),
  q("Name a film composer whose music you'd know in a few notes.", [
    f("John Williams", ["williams", "star wars composer", "john williams the composer"]),
    f("Hans Zimmer", ["zimmer", "inception composer", "hans zimmer the composer"]),
    f("Ennio Morricone", ["morricone", "ennio", "spaghetti western composer"]),
    f("Howard Shore", ["lord of the rings composer", "howard shore the composer"]),
    f("Danny Elfman", ["elfman", "batman theme composer", "danny elfman the composer"]),
    f("James Horner", ["horner", "titanic composer", "james horner the composer"]),
    f("Alan Silvestri", ["silvestri", "back to the future composer", "alan silvestri the composer"]),
    f("Bernard Herrmann", ["herrmann", "psycho composer", "bernard herrmann the composer"]),
    f("Vangelis", ["vangelis papathanassiou", "chariots of fire composer", "blade runner composer"]),
    f("Jerry Goldsmith", ["goldsmith", "alien composer", "jerry goldsmith the composer"]),
    f("Nino Rota", ["rota", "godfather composer", "nino rota the composer"]),
    f("Michael Giacchino", ["giacchino", "up composer", "michael giacchino the composer"]),
    f("Ludwig Göransson", ["ludwig goransson", "goransson", "oppenheimer composer"]),
    f("Alexandre Desplat", ["desplat", "grand budapest composer", "alexandre desplat the composer"]),
    f("Thomas Newman", ["thomas newman the composer", "shawshank composer"]),
    f("Randy Newman", ["randy newman the composer", "toy story composer", "you've got a friend in me composer"]),
  ]),
  q("Name an actor known for playing tough guys.", [
    f("Arnold Schwarzenegger", ["schwarzenegger", "arnie", "the terminator actor"]),
    f("Sylvester Stallone", ["stallone", "sly stallone", "rocky actor"]),
    f("Bruce Willis", ["willis", "die hard actor", "bruce willis the actor"]),
    f("Jason Statham", ["statham", "the transporter actor", "jason statham the actor"]),
    f("Clint Eastwood", ["eastwood", "dirty harry actor", "clint eastwood the actor"]),
    f("Vin Diesel", ["diesel", "dom toretto actor", "vin diesel the actor"]),
    f("Jean-Claude Van Damme", ["van damme", "jcvd", "muscles from brussels"]),
    f("Dwayne Johnson", ["the rock", "dwayne the rock johnson", "rock johnson"]),
    f("Charles Bronson", ["bronson", "death wish actor", "charles bronson the actor"]),
    f("Liam Neeson", ["neeson", "taken actor", "liam neeson the actor"]),
    f("Steven Seagal", ["seagal", "under siege actor", "steven seagal the actor"]),
    f("Bruce Lee", ["enter the dragon actor", "bruce lee the actor"]),
    f("Chuck Norris", ["norris", "walker texas ranger actor", "chuck norris the actor"]),
    f("Mel Gibson", ["gibson", "lethal weapon actor", "mel gibson the actor"]),
    f("Keanu Reeves", ["keanu", "reeves", "john wick actor"]),
    f("Jackie Chan", ["chan", "rush hour actor", "jackie chan the actor"]),
  ]),
  q("Name an actor famous for comedy.", [
    f("Jim Carrey", ["carrey", "ace ventura actor", "jim carrey the actor"]),
    f("Adam Sandler", ["sandler", "happy gilmore actor", "adam sandler the actor"]),
    f("Eddie Murphy", ["murphy", "beverly hills cop actor", "eddie murphy the actor"]),
    f("Robin Williams", ["williams", "mrs doubtfire actor", "robin williams the actor"]),
    f("Will Ferrell", ["ferrell", "anchorman actor", "will ferrell the actor"]),
    f("Steve Carell", ["carell", "the office actor", "steve carell the actor"]),
    f("Ben Stiller", ["stiller", "zoolander actor", "ben stiller the actor"]),
    f("Mike Myers", ["myers", "austin powers actor", "mike myers the actor"]),
    f("Kevin Hart", ["kevin hart the comedian", "jumanji comedian"]),
    f("Rowan Atkinson", ["atkinson", "mr bean actor", "rowan atkinson the actor"]),
    f("Bill Murray", ["murray", "ghostbusters actor", "bill murray the actor"]),
    f("Jack Black", ["school of rock actor", "jack black the actor"]),
    f("Melissa McCarthy", ["mccarthy", "bridesmaids actress", "melissa mccarthy the actress"]),
    f("Steve Martin", ["the jerk actor", "steve martin the actor"]),
    f("Kristen Wiig", ["wiig", "bridesmaids star", "kristen wiig the actress"]),
    f("Chevy Chase", ["vacation actor", "chevy chase the actor"]),
  ]),
];
