import { family as f, question as q } from "./common.mjs";

export const general = [
  q("Name a small ritual that makes a morning feel started.", [
    f("Coffee", ["brew", "morning coffee"]),
    f("A shower", ["shower", "morning wash"]),
    f("Stretching", ["stretch", "warm-up"]),
    f("Checking the phone", ["phone check", "check messages"]),
    f("Breakfast", ["morning meal", "first meal"]),
    f("A walk outside", ["outdoor walk", "stroll"]),
    f("Music", ["songs", "tunes"]),
    f("Journaling", ["keeping a journal", "morning pages"]),
    f("Fresh fruit", ["fruit", "morning fruit"]),
    f("Water", ["glass of water", "hydration"]),
    f("Meditation", ["mindfulness", "quiet meditation"]),
    f("Sunlight", ["morning light", "sunshine"]),
    f("Making the bed", ["bed making", "tidy the bed"]),
    f("Tea", ["cup of tea", "morning tea"]),
    f("Reading the news", ["news reading", "morning headlines"]),
    f("Planning the day", ["daily plan", "making a schedule"]),
  ]),
  q("What is something people keep in a junk drawer?", [
    f("Batteries", ["power cells", "AA batteries"]),
    f("Rubber bands", ["elastic bands", "rubber loops"]),
    f("Takeout menus", ["delivery menus", "restaurant menus"]),
    f("Loose keys", ["spare keys", "old keys"]),
    f("A screwdriver", ["hand screwdriver", "flathead tool"]),
    f("Old receipts", ["past receipts", "shopping slips"]),
    f("Buttons", ["spare buttons", "sewing buttons"]),
    f("A tape measure", ["measuring tape", "tape ruler"]),
    f("Spare change", ["loose coins", "pocket change"]),
    f("Safety pins", ["sewing pins", "fastening pins"]),
    f("A flashlight", ["torch", "hand torch"]),
    f("Pens", ["ballpoint pens", "writing pens"]),
    f("A small notepad", ["pocket notebook", "little notebook"]),
    f("USB drives", ["memory sticks", "flash drives"]),
    f("Tape", ["sticky tape", "adhesive tape"]),
    f("A utility knife", ["box cutter", "craft knife"]),
  ]),
  q("Name a food you reach for when you want comfort.", [
    f("Mac and cheese", ["macaroni cheese", "cheesy pasta"]),
    f("Soup", ["warm soup", "a bowl of soup"]),
    f("Pizza", ["pizza pie", "a slice"]),
    f("Ice cream", ["frozen dessert", "a scoop"]),
    f("Toast", ["buttered toast", "toast bread"]),
    f("Chocolate", ["chocolate bar", "cocoa treat"]),
    f("Noodles", ["noodle bowl", "pasta noodles"]),
    f("Mashed potatoes", ["mashed spuds", "potato mash"]),
    f("Fried chicken", ["crispy chicken", "chicken pieces"]),
    f("Grilled cheese", ["cheese toastie", "toasted sandwich"]),
    f("Rice pudding", ["sweet rice", "rice dessert"]),
    f("Curry", ["warm curry", "spiced stew"]),
    f("Dumplings", ["steamed dumplings", "filled dumplings"]),
    f("Pancakes", ["flapjacks", "hotcakes"]),
    f("Apple pie", ["apple tart", "fruit pie"]),
    f("A baked potato", ["jacket potato", "baked spud"]),
  ]),
  q("What belongs in a beach bag?", [
    f("Sunscreen", ["sun lotion", "SPF lotion"]),
    f("A towel", ["beach towel", "bathing towel"]),
    f("Water", ["drinking water", "water bottle"]),
    f("Sunglasses", ["sun glasses", "shades"]),
    f("A book", ["beach read", "paperback"]),
    f("Snacks", ["beach snacks", "small bites"]),
    f("Flip-flops", ["thongs sandals", "rubber sandals"]),
    f("A hat", ["sun hat", "beach hat"]),
    f("A swimsuit", ["bathing suit", "swimwear"]),
    f("A beach mat", ["sand mat", "picnic mat"]),
    f("A change of clothes", ["spare clothes", "dry clothes"]),
    f("A water-resistant pouch", ["dry pouch", "waterproof bag"]),
    f("A camera", ["beach camera", "photo camera"]),
    f("A beach ball", ["inflatable ball", "play ball"]),
    f("A shell bag", ["shell collection bag", "small beach bag"]),
    f("After-sun lotion", ["sunburn cream", "cooling lotion"]),
  ]),
  q("Name something people do while waiting in a queue.", [
    f("Scroll on the phone", ["Scroll phone", "phone scrolling"]),
    f("Chat", ["talk", "make conversation"]),
    f("People-watch", ["watch people", "observe the crowd"]),
    f("Read", ["read a book", "look at reading"]),
    f("Listen to music", ["hear songs", "use headphones"]),
    f("Check the time", ["watch the clock", "look at time"]),
    f("Look around", ["scan the room", "look about"]),
    f("Play a game", ["play on the phone", "do a game"]),
    f("Plan the day", ["make plans", "organize the day"]),
    f("Count the people", ["count the line", "number the queue"]),
    f("Check email", ["read email", "open the inbox"]),
    f("Browse a shop", ["look at products", "window shop"]),
    f("Drink water", ["take a drink", "sip water"]),
    f("Take a selfie", ["snap a selfie", "self portrait"]),
    f("Fidget", ["tap fingers", "shift around"]),
    f("Leave the line", ["step out", "abandon the queue"]),
  ]),
  q("What is a smell that instantly feels nostalgic?", [
    f("Fresh bread", ["baking bread", "bread from the oven"]),
    f("Rain", ["rainfall", "wet pavement"]),
    f("Sunscreen", ["sun lotion", "holiday lotion"]),
    f("Cut grass", ["mown grass", "freshly cut lawn"]),
    f("Grandparent's house", ["grandparents' home", "grandma's house"]),
    f("Chlorine", ["pool smell", "swimming pool"]),
    f("Wood smoke", ["fireplace smoke", "campfire scent"]),
    f("Crayons", ["wax crayons", "crayon box"]),
    f("Old books", ["book smell", "aged paper"]),
    f("Coffee", ["coffee beans", "brewed coffee"]),
    f("Fresh paint", ["new paint", "paint fumes"]),
    f("Sea air", ["ocean breeze", "salt air"]),
    f("Laundry soap", ["clean laundry", "washing powder"]),
    f("A school hallway", ["school smell", "classroom scent"]),
    f("Cinnamon", ["cinnamon spice", "baking cinnamon"]),
    f("Petrol", ["gasoline", "fuel smell"]),
  ]),
  q("Name a tiny luxury that improves an ordinary day.", [
    f("A hot coffee", ["fresh coffee", "steaming coffee"]),
    f("Clean sheets", ["fresh bedding", "newly washed sheets"]),
    f("A long bath", ["relaxing bath", "soaking bath"]),
    f("A pastry", ["sweet pastry", "morning pastry"]),
    f("Fresh flowers", ["cut flowers", "a flower bouquet"]),
    f("A quiet hour", ["peaceful hour", "some quiet time"]),
    f("Good headphones", ["quality headphones", "nice earphones"]),
    f("A window seat", ["seat by the window", "window-side seat"]),
    f("A slow breakfast", ["unhurried breakfast", "leisurely breakfast"]),
    f("A fancy chocolate", ["premium chocolate", "special chocolate"]),
    f("A nap", ["short sleep", "afternoon nap"]),
    f("A candle", ["scented candle", "lighting a candle"]),
    f("A favorite playlist", ["comfort playlist", "music mix"]),
    f("A warm blanket", ["cozy blanket", "soft throw"]),
    f("A handwritten note", ["personal note", "little letter"]),
    f("A seat upgrade", ["better seat", "premium seat"]),
  ]),
  q("What could you find under a sofa?", [
    f("Coins", ["loose change", "small coins"]),
    f("Dust", ["dust bunnies", "floor dust"]),
    f("A lost remote", ["remote control", "TV remote"]),
    f("A sock", ["single sock", "odd sock"]),
    f("Crumbs", ["food crumbs", "snack crumbs"]),
    f("A toy", ["children's toy", "small toy"]),
    f("A book", ["lost book", "paperback book"]),
    f("A hair tie", ["elastic hair band", "ponytail band"]),
    f("A slipper", ["house slipper", "lost slipper"]),
    f("A pet toy", ["dog toy", "cat toy"]),
    f("A pen", ["lost pen", "ballpoint"]),
    f("A bottle cap", ["drink cap", "plastic cap"]),
    f("A receipt", ["old receipt", "shopping receipt"]),
    f("A charger", ["phone charger", "charging cable"]),
    f("A puzzle piece", ["missing puzzle piece", "jigsaw piece"]),
    f("A button", ["loose button", "coat button"]),
  ]),
  q("Name a rainy-day reset.", [
    f("A nap", ["short sleep", "rainy nap"]),
    f("A movie", ["watch a film", "film night"]),
    f("Baking", ["bake something", "oven baking"]),
    f("Reading", ["read a book", "book time"]),
    f("A hot drink", ["warm beverage", "hot cup"]),
    f("A long shower", ["rainy shower", "steamy shower"]),
    f("Tidying up", ["cleaning up", "straightening the room"]),
    f("Board games", ["tabletop games", "play a board game"]),
    f("A walk in the rain", ["rain walk", "wet-weather walk"]),
    f("A playlist", ["music session", "listening session"]),
    f("A warm blanket", ["cozy throw", "soft blanket"]),
    f("Soup making", ["cook soup", "soup pot"]),
    f("Journaling", ["write in a journal", "rainy notes"]),
    f("A puzzle", ["jigsaw puzzle", "do a puzzle"]),
    f("A phone call", ["call a friend", "chat on the phone"]),
    f("Lighting a candle", ["light candles", "candle time"]),
  ]),
  q("What is something people collect?", [
    f("Stamps", ["postage stamps", "stamp collection"]),
    f("Books", ["novels", "book collection"]),
    f("Coins", ["old coins", "coin collection"]),
    f("Postcards", ["travel postcards", "picture cards"]),
    f("Vinyl records", ["record albums", "LPs"]),
    f("Magnets", ["fridge magnets", "souvenir magnets"]),
    f("Sneakers", ["trainers", "shoe collection"]),
    f("Sea glass", ["beach glass", "tumbled glass"]),
    f("Comic books", ["comics", "graphic issues"]),
    f("Action figures", ["collectible figures", "toy figures"]),
    f("Shells", ["seashells", "shell collection"]),
    f("Cups", ["mugs", "cup collection"]),
    f("Rocks", ["stones", "rock collection"]),
    f("Photographs", ["printed photos", "picture collection"]),
    f("Pins", ["enamel pins", "pin badges"]),
    f("Recipes", ["recipe cards", "cooking recipes"]),
  ]),
  q("What might a guest bring to a casual gathering?", [
    f("Wine", ["a bottle of wine", "red wine"]),
    f("Dessert", ["sweet course", "something sweet"]),
    f("Flowers", ["a bouquet", "fresh flowers"]),
    f("Chips", ["crisps", "potato chips"]),
    f("A board game", ["tabletop game", "party game"]),
    f("Fruit", ["fresh fruit", "fruit bowl"]),
    f("Bread", ["fresh loaf", "a loaf"]),
    f("A playlist", ["music mix", "party playlist"]),
    f("Beer", ["bottled beer", "a six-pack"]),
    f("Cheese", ["cheese board", "soft cheese"]),
    f("A houseplant", ["potted plant", "indoor plant"]),
    f("A salad", ["green salad", "mixed salad"]),
    f("Ice", ["ice cubes", "a bag of ice"]),
    f("Napkins", ["paper napkins", "serviettes"]),
    f("A candle", ["gift candle", "scented candle"]),
    f("A homemade dish", ["home cooking", "cooked food"]),
  ]),
  q("Name an item often found on a desk.", [
    f("A notebook", ["writing notebook", "notepad"]),
    f("A pen", ["ballpoint", "ink pen"]),
    f("A laptop", ["notebook computer", "work computer"]),
    f("A mug", ["coffee mug", "tea cup"]),
    f("Sticky notes", ["memo notes", "post-it notes"]),
    f("A lamp", ["desk lamp", "reading lamp"]),
    f("Headphones", ["headset", "earphones"]),
    f("A plant", ["desk plant", "houseplant"]),
    f("A keyboard", ["computer keyboard", "typing board"]),
    f("A mouse", ["computer mouse", "pointing mouse"]),
    f("A charger", ["power charger", "charging lead"]),
    f("A calendar", ["desk calendar", "date planner"]),
    f("A water bottle", ["drinking bottle", "desk bottle"]),
    f("Paper clips", ["metal clips", "binder clips"]),
    f("A stapler", ["desk stapler", "staple gun"]),
    f("A calculator", ["desk calculator", "number machine"]),
  ]),
  q("What is a sound people notice at night?", [
    f("Rain", ["rainfall", "rain drops"]),
    f("Traffic", ["road noise", "cars outside"]),
    f("A fan", ["electric fan", "fan hum"]),
    f("Crickets", ["cricket song", "insects chirping"]),
    f("A dog barking", ["barking dog", "dog noise"]),
    f("Footsteps", ["walking sounds", "steps"]),
    f("The refrigerator", ["fridge hum", "refrigerator noise"]),
    f("Wind", ["wind outside", "breeze"]),
    f("A train", ["train whistle", "railway noise"]),
    f("An owl", ["owl hoot", "night bird"]),
    f("A clock", ["clock ticking", "tick tock"]),
    f("Neighbors", ["neighbor noise", "people next door"]),
    f("Pipes", ["water pipes", "plumbing sounds"]),
    f("A phone notification", ["message alert", "phone ping"]),
    f("Thunder", ["storm rumble", "thunderclap"]),
    f("Silence", ["quiet", "the absence of sound"]),
  ]),
  q("Name a way to celebrate good news.", [
    f("Call a friend", ["phone a friend", "make a happy call"]),
    f("Go out for dinner", ["eat out", "celebration meal"]),
    f("Open champagne", ["pop a bottle", "drink bubbly"]),
    f("Post online", ["share the news", "make a post"]),
    f("Buy a treat", ["get a dessert", "treat yourself"]),
    f("Hug someone", ["give a hug", "celebration hug"]),
    f("Take a trip", ["go away", "celebration trip"]),
    f("Dance", ["have a dance", "dance around"]),
    f("Throw a party", ["host a party", "celebration party"]),
    f("Send flowers", ["give flowers", "flower delivery"]),
    f("Make a toast", ["raise a glass", "give a toast"]),
    f("Take a photo", ["snap a picture", "celebration photo"]),
    f("Ring family", ["call family", "tell the family"]),
    f("Buy a gift", ["treat someone", "celebration present"]),
    f("Have a quiet smile", ["smile to yourself", "happy smile"]),
    f("Write it down", ["record the news", "make a note"]),
  ]),
  q("What is something people do before bed?", [
    f("Brush their teeth", ["brush teeth", "clean their teeth"]),
    f("Read", ["read a book", "bedtime reading"]),
    f("Set an alarm", ["set the alarm", "alarm clock"]),
    f("Check messages", ["read texts", "check the phone"]),
    f("Wash their face", ["clean their face", "face wash"]),
    f("Drink water", ["have water", "water before sleep"]),
    f("Stretch", ["do stretches", "bedtime stretch"]),
    f("Lock the door", ["check the lock", "secure the house"]),
    f("Change into pajamas", ["put on pajamas", "get into pyjamas"]),
    f("Set out clothes", ["choose tomorrow's clothes", "lay out clothes"]),
    f("Turn off lights", ["switch off lights", "darken the room"]),
    f("Take medicine", ["have medication", "night medicine"]),
    f("Set a sleep timer", ["sleep timer", "timer for sleep"]),
    f("Say goodnight", ["wish goodnight", "tell someone goodnight"]),
    f("Feed the pet", ["give the pet food", "pet bedtime meal"]),
    f("Think about tomorrow", ["plan tomorrow", "prepare for tomorrow"]),
  ]),
  q("What might you pack for a picnic?", [
    f("Sandwiches", ["packed sandwiches", "picnic sandwich"]),
    f("Fruit", ["fresh fruit", "cut fruit"]),
    f("A blanket", ["picnic blanket", "ground blanket"]),
    f("Water", ["water bottle", "drinking water"]),
    f("Napkins", ["paper napkins", "picnic serviettes"]),
    f("A basket", ["picnic basket", "food basket"]),
    f("Chips", ["crisps", "snack chips"]),
    f("Sunscreen", ["sun lotion", "SPF cream"]),
    f("Cups", ["plastic cups", "drinking cups"]),
    f("Cutlery", ["plastic forks", "eating utensils"]),
    f("A cooler", ["cool box", "ice chest"]),
    f("Cheese", ["picnic cheese", "cheese pieces"]),
    f("A frisbee", ["flying disc", "throwing disc"]),
    f("A camera", ["picnic camera", "photo camera"]),
    f("A thermos", ["flask", "hot drink flask"]),
    f("A rubbish bag", ["trash bag", "waste bag"]),
  ]),
  q("Name something people lose at home.", [
    f("Keys", ["house keys", "lost keys"]),
    f("The remote", ["remote control", "TV remote"]),
    f("Glasses", ["spectacles", "reading glasses"]),
    f("A phone", ["mobile phone", "cell phone"]),
    f("Socks", ["odd socks", "missing socks"]),
    f("A wallet", ["purse", "money wallet"]),
    f("A charger", ["charging cable", "phone charger"]),
    f("A receipt", ["shopping receipt", "paper receipt"]),
    f("A hairbrush", ["brush", "hair brush"]),
    f("A toy", ["children's toy", "plaything"]),
    f("A pen", ["writing pen", "lost ballpoint"]),
    f("A book", ["paperback", "misplaced book"]),
    f("Jewelry", ["jewellery", "rings and earrings"]),
    f("A passport", ["travel document", "passport booklet"]),
    f("A hearing aid", ["earpiece", "hearing device"]),
    f("A hair tie", ["hair band", "elastic band"]),
  ]),
  q("Name an item you might find on a keyring.", [
    f("House keys", ["door keys", "home keys"]),
    f("A car key", ["vehicle key", "car fob"]),
    f("A bottle opener", ["keyring opener", "bar blade"]),
    f("A flashlight", ["keychain torch", "tiny torch"]),
    f("A charm", ["key charm", "small ornament"]),
    f("A photo", ["photo tag", "picture insert"]),
    f("A loyalty tag", ["membership tag", "store fob"]),
    f("A whistle", ["key whistle", "small whistle"]),
    f("A USB drive", ["keychain drive", "memory stick"]),
    f("A tracking tag", ["locator tag", "item tracker"]),
    f("A key cover", ["rubber key cover", "key sleeve"]),
    f("A badge", ["identity badge", "small badge"]),
    f("A coin", ["lucky coin", "keyring coin"]),
    f("A tape measure", ["mini tape measure", "keychain ruler"]),
    f("A hand sanitizer", ["sanitizer bottle", "pocket sanitizer"]),
    f("A ring", ["metal ring", "key ring"]),
  ]),
  q("Name an excuse people use to leave the house.", [
    f("Run an errand", ["do an errand", "quick errand"]),
    f("Walk the dog", ["take out the dog", "dog walk"]),
    f("Buy groceries", ["get groceries", "food shopping"]),
    f("Get coffee", ["buy coffee", "coffee run"]),
    f("Meet a friend", ["see a friend", "friend meetup"]),
    f("Go to work", ["commute to work", "head to work"]),
    f("Exercise", ["work out", "go running"]),
    f("Post a letter", ["mail a letter", "visit the post office"]),
    f("Get fresh air", ["go outside", "take the air"]),
    f("Pick up medicine", ["collect medication", "pharmacy trip"]),
    f("Return something", ["make a return", "return a purchase"]),
    f("Go to the library", ["visit the library", "library trip"]),
    f("Buy fuel", ["fill the car", "fuel stop"]),
    f("Attend an appointment", ["go to an appointment", "medical visit"]),
    f("Take a drive", ["go for a drive", "car ride"]),
    f("See a movie", ["go to the cinema", "film outing"]),
  ]),
  q("What might appear at a weekend breakfast?", [
    f("Eggs", ["fried eggs", "scrambled eggs"]),
    f("Bacon", ["crispy bacon", "streaky bacon"]),
    f("Toast", ["buttered toast", "toast slices"]),
    f("Pancakes", ["flapjacks", "breakfast pancakes"]),
    f("Cereal", ["breakfast cereal", "a bowl of cereal"]),
    f("Fruit", ["fresh fruit", "fruit plate"]),
    f("Coffee", ["fresh coffee", "morning brew"]),
    f("Juice", ["orange juice", "fruit juice"]),
    f("Yogurt", ["yoghurt", "breakfast yogurt"]),
    f("Sausages", ["breakfast sausage", "links"]),
    f("Mushrooms", ["fried mushrooms", "breakfast mushrooms"]),
    f("Avocado", ["avocado toast", "sliced avocado"]),
    f("Beans", ["baked beans", "breakfast beans"]),
    f("Pastries", ["croissants", "breakfast pastries"]),
    f("Hash browns", ["potato hash", "breakfast potatoes"]),
    f("Jam", ["fruit preserve", "toast jam"]),
  ]),
  q("Name a hobby someone might try.", [
    f("Painting", ["making art", "watercolor painting"]),
    f("Gardening", ["growing plants", "garden work"]),
    f("Cooking", ["making food", "home cooking"]),
    f("Photography", ["taking photos", "camera hobby"]),
    f("Running", ["jogging", "going for runs"]),
    f("Knitting", ["making knitwear", "needle knitting"]),
    f("Reading", ["book reading", "reading books"]),
    f("Playing guitar", ["guitar practice", "strumming guitar"]),
    f("Birdwatching", ["watching birds", "bird spotting"]),
    f("Baking", ["baking cakes", "oven baking"]),
    f("Cycling", ["bike riding", "riding a bicycle"]),
    f("Drawing", ["sketching", "making drawings"]),
    f("Dancing", ["dance practice", "learning dance"]),
    f("Fishing", ["going fishing", "angling"]),
    f("Chess", ["playing chess", "chess games"]),
    f("Writing", ["creative writing", "writing stories"]),
  ]),
  q("Name something people do while on holiday.", [
    f("Swim", ["go swimming", "take a swim"]),
    f("Sightsee", ["visit sights", "see landmarks"]),
    f("Relax", ["take it easy", "rest"]),
    f("Take photos", ["photograph places", "snap pictures"]),
    f("Eat local food", ["try local dishes", "taste the cuisine"]),
    f("Go shopping", ["shop for souvenirs", "browse shops"]),
    f("Visit a museum", ["see a museum", "museum trip"]),
    f("Read by the pool", ["poolside reading", "read on holiday"]),
    f("Hike", ["go hiking", "walk a trail"]),
    f("Sunbathe", ["lie in the sun", "get a tan"]),
    f("Take a boat trip", ["go boating", "boat excursion"]),
    f("Meet locals", ["talk to locals", "make local friends"]),
    f("Sleep late", ["lie in", "sleep in"]),
    f("Send postcards", ["mail postcards", "write holiday cards"]),
    f("Rent a car", ["hire a car", "get a rental car"]),
    f("Try an activity", ["do an excursion", "holiday adventure"]),
  ]),
  q("What might be in a medicine cabinet?", [
    f("Bandages", ["plasters", "adhesive bandages"]),
    f("Painkillers", ["pain medicine", "headache tablets"]),
    f("Antiseptic", ["disinfectant", "wound cleaner"]),
    f("Thermometer", ["temperature checker", "fever thermometer"]),
    f("Cough syrup", ["cough medicine", "syrup for coughs"]),
    f("Vitamins", ["vitamin tablets", "supplements"]),
    f("Tweezers", ["small tweezers", "eyebrow tweezers"]),
    f("Cotton swabs", ["cotton buds", "ear swabs"]),
    f("A first-aid kit", ["medical kit", "emergency kit"]),
    f("Hand sanitizer", ["alcohol gel", "sanitizing gel"]),
    f("Allergy tablets", ["antihistamines", "hay fever pills"]),
    f("Sunscreen", ["sun cream", "SPF lotion"]),
    f("A hot-water bottle", ["heat bottle", "warm water bottle"]),
    f("Eye drops", ["eye medicine", "drops for eyes"]),
    f("Gauze", ["medical gauze", "wound dressing"]),
    f("Prescription medicine", ["prescription drugs", "regular medication"]),
  ]),
  q("Name a way to apologize.", [
    f("Say sorry", ["apologize", "offer an apology"]),
    f("Write a note", ["send a letter", "apology note"]),
    f("Give a hug", ["hug someone", "make up with a hug"]),
    f("Buy a gift", ["give a present", "apology present"]),
    f("Make it right", ["fix the mistake", "put things right"]),
    f("Explain yourself", ["give an explanation", "explain what happened"]),
    f("Listen", ["hear them out", "listen carefully"]),
    f("Change behavior", ["do better", "act differently"]),
    f("Make a phone call", ["call to apologize", "apology call"]),
    f("Bring flowers", ["send flowers", "apology bouquet"]),
    f("Offer a refund", ["return the money", "give a refund"]),
    f("Cook dinner", ["make a meal", "apology dinner"]),
    f("Give space", ["allow some space", "step back"]),
    f("Admit fault", ["own the mistake", "take responsibility"]),
    f("Send a message", ["text sorry", "apology text"]),
    f("Promise to improve", ["commit to change", "make a promise"]),
  ]),
  q("What might you find in a car?", [
    f("A spare tire", ["emergency tire", "spare wheel"]),
    f("A first-aid kit", ["car medical kit", "emergency kit"]),
    f("Sunglasses", ["driving glasses", "sun shades"]),
    f("A phone charger", ["car charger", "charging cable"]),
    f("A map", ["road map", "paper map"]),
    f("Tissues", ["paper tissues", "face tissues"]),
    f("A water bottle", ["drinking bottle", "car water"]),
    f("Coins", ["loose change", "parking coins"]),
    f("A flashlight", ["car torch", "emergency torch"]),
    f("An umbrella", ["rain umbrella", "car umbrella"]),
    f("A blanket", ["car blanket", "emergency blanket"]),
    f("A parking ticket", ["parking receipt", "pay-and-display ticket"]),
    f("A child seat", ["car seat", "booster seat"]),
    f("A cleaning cloth", ["car cloth", "dashboard cloth"]),
    f("An air freshener", ["car freshener", "scent hanger"]),
    f("A road atlas", ["driving atlas", "map book"]),
  ]),
  q("Name something people photograph.", [
    f("Food", ["meals", "food photos"]),
    f("Sunsets", ["sunset pictures", "evening sky"]),
    f("Pets", ["animals", "pet pictures"]),
    f("Friends", ["group photos", "people pictures"]),
    f("Landmarks", ["famous sights", "monuments"]),
    f("Flowers", ["flower pictures", "plants"]),
    f("Their children", ["kids", "child photos"]),
    f("Selfies", ["self-portraits", "self pictures"]),
    f("The sea", ["ocean pictures", "water photos"]),
    f("Buildings", ["architecture", "building photos"]),
    f("Concerts", ["live shows", "music events"]),
    f("Receipts", ["proof of purchase", "receipt pictures"]),
    f("Outfits", ["clothes", "fashion photos"]),
    f("A new home", ["house pictures", "home photos"]),
    f("Street art", ["murals", "urban art"]),
    f("A reflection", ["mirror picture", "reflection photo"]),
  ]),
  q("What is a cold-weather comfort?", [
    f("Hot chocolate", ["cocoa", "warm chocolate"]),
    f("A blanket", ["cozy blanket", "soft throw"]),
    f("A fireplace", ["open fire", "fireplace heat"]),
    f("Warm socks", ["wool socks", "thick socks"]),
    f("Soup", ["hot soup", "soup bowl"]),
    f("Tea", ["hot tea", "warm cup of tea"]),
    f("A sweater", ["warm jumper", "wool sweater"]),
    f("A bath", ["hot bath", "warm soak"]),
    f("A heated room", ["central heating", "warm room"]),
    f("A scarf", ["wool scarf", "neck scarf"]),
    f("Baked food", ["oven food", "something baked"]),
    f("A duvet", ["thick duvet", "warm bedding"]),
    f("Slippers", ["house shoes", "warm slippers"]),
    f("Candlelight", ["lit candles", "candle glow"]),
    f("A book", ["winter reading", "good book"]),
    f("A warm pet", ["pet cuddle", "cuddling the dog"]),
  ]),
  q("Name something you might see at a party.", [
    f("Music", ["party songs", "a playlist"]),
    f("Dancing", ["people dancing", "party dancing"]),
    f("Cake", ["party cake", "birthday cake"]),
    f("Balloons", ["party balloons", "inflated balloons"]),
    f("Drinks", ["party drinks", "beverages"]),
    f("Snacks", ["party food", "finger food"]),
    f("Friends", ["guests", "people you know"]),
    f("Games", ["party games", "group games"]),
    f("Decorations", ["party decor", "festive decorations"]),
    f("Candles", ["cake candles", "lit candles"]),
    f("A speaker", ["music speaker", "loudspeaker"]),
    f("Gifts", ["presents", "wrapped gifts"]),
    f("A photo booth", ["photo corner", "party photo booth"]),
    f("Confetti", ["party confetti", "paper confetti"]),
    f("A host", ["party host", "event organizer"]),
    f("A dance floor", ["place to dance", "party floor"]),
  ]),
  q("What is a reason someone might open a window?", [
    f("Let in fresh air", ["air the room", "get fresh air"]),
    f("Cool the room", ["let out heat", "bring in cool air"]),
    f("Hear outside", ["listen outdoors", "hear the street"]),
    f("Smell rain", ["enjoy rain air", "smell the weather"]),
    f("Talk to someone", ["speak through the window", "call out"]),
    f("Feed a bird", ["give food to birds", "bird feeding"]),
    f("See the view", ["look outside", "check the street"]),
    f("Let out smoke", ["clear smoke", "vent the room"]),
    f("Water plants", ["reach the window plants", "water flowers"]),
    f("Listen for a noise", ["check a sound", "hear what happened"]),
    f("Clean the glass", ["wash the window", "clean the pane"]),
    f("Hang decorations", ["put up a decoration", "decorate the window"]),
    f("Call the cat", ["let the cat in", "invite the cat"]),
    f("Watch the sunset", ["see sunset", "look at evening light"]),
    f("Dry laundry", ["air clothes", "dry washing"]),
    f("Escape a smell", ["vent an odor", "clear bad smell"]),
  ]),
  q("What might be in a backpack?", [
    f("A notebook", ["school notebook", "writing pad"]),
    f("Pens", ["writing pens", "ink pens"]),
    f("A laptop", ["portable computer", "work laptop"]),
    f("Water", ["water bottle", "drinking water"]),
    f("Snacks", ["packed snacks", "food bars"]),
    f("A book", ["paperback", "reading book"]),
    f("A charger", ["charging cable", "phone charger"]),
    f("A wallet", ["purse", "money wallet"]),
    f("Keys", ["house keys", "keyring"]),
    f("Headphones", ["earbuds", "music headphones"]),
    f("An umbrella", ["rain umbrella", "folding umbrella"]),
    f("A jacket", ["light coat", "spare jacket"]),
    f("A lunchbox", ["packed lunch", "food box"]),
    f("Tissues", ["paper tissues", "pocket tissues"]),
    f("A pencil case", ["pen case", "stationery pouch"]),
    f("Hand sanitizer", ["sanitizing gel", "clean hands gel"]),
  ]),
];
