import { family as f, question as q } from "./common.mjs";

export const geography = [
  q("Name a place people go to escape hot weather.", [
    f("The mountains", ["mountain air", "highlands"]),
    f("The beach", ["seaside", "coast"]),
    f("A forest", ["woodland", "tree-covered place"]),
    f("An air-conditioned mall", ["cool shopping center", "shopping mall"]),
    f("A lake", ["lakeside", "lake shore"]),
    f("The Arctic", ["polar region", "far north"]),
    f("A swimming pool", ["pool", "cool water"]),
    f("A cave", ["underground cave", "cavern"]),
    f("A waterfall", ["waterfall pool", "falls"]),
    f("A river", ["riverside", "river bank"]),
    f("A museum", ["cool museum", "indoor gallery"]),
    f("The cinema", ["movie theater", "film house"]),
    f("A shaded park", ["park shade", "tree-shaded park"]),
    f("A northern city", ["cool northern town", "high-latitude city"]),
    f("An underground station", ["subway station", "metro underground"]),
    f("A glacier", ["ice field", "frozen glacier"]),
  ]),
  q("What landscape might you cross on a long train journey?", [
    f("Fields", ["farmland", "open fields"]),
    f("Mountains", ["mountain range", "high peaks"]),
    f("Desert", ["arid land", "sand desert"]),
    f("Forest", ["woodland", "tree country"]),
    f("Coastline", ["coastal land", "sea coast"]),
    f("Prairie", ["grassland", "open prairie"]),
    f("Suburbs", ["suburban area", "outer neighborhoods"]),
    f("Tundra", ["arctic tundra", "treeless plain"]),
    f("A river valley", ["valley floor", "river basin"]),
    f("Wetlands", ["marshland", "swamp country"]),
    f("Vineyards", ["wine country", "vineyard fields"]),
    f("Rolling hills", ["hill country", "soft hills"]),
    f("A canyon", ["deep gorge", "canyon land"]),
    f("A lake district", ["lake country", "many lakes"]),
    f("Industrial towns", ["factory towns", "industrial belt"]),
    f("Snowfields", ["snowy plain", "snow country"]),
  ]),
  q("Name something you might see at a harbor.", [
    f("Boats", ["small boats", "harbor vessels"]),
    f("Cranes", ["cargo cranes", "port cranes"]),
    f("Lighthouses", ["harbor lighthouse", "beacon tower"]),
    f("Gulls", ["seagulls", "sea birds"]),
    f("Containers", ["shipping containers", "cargo boxes"]),
    f("Ferries", ["ferry boats", "passenger ferries"]),
    f("Ropes", ["mooring ropes", "dock ropes"]),
    f("A fish market", ["seafood market", "harbor market"]),
    f("A pier", ["harbor pier", "dock"]),
    f("Sailors", ["ship crews", "seafarers"]),
    f("Buoys", ["channel buoys", "floating markers"]),
    f("A breakwater", ["harbor wall", "sea barrier"]),
    f("A shipyard", ["boat yard", "ship building yard"]),
    f("Fishing nets", ["fish nets", "trawling nets"]),
    f("A customs office", ["port customs", "customs house"]),
    f("A cargo ship", ["freighter", "container ship"]),
  ]),
  q("What can make a city feel like a capital?", [
    f("Government buildings", ["state buildings", "public offices"]),
    f("A grand avenue", ["ceremonial boulevard", "main avenue"]),
    f("Museums", ["national museums", "city museums"]),
    f("Embassies", ["foreign embassies", "diplomatic missions"]),
    f("A palace", ["royal palace", "presidential palace"]),
    f("Monuments", ["national monuments", "public memorials"]),
    f("Busy transit", ["major transport", "urban transit"]),
    f("A national library", ["state library", "central library"]),
    f("A parliament", ["legislative building", "assembly hall"]),
    f("A cathedral", ["great church", "capital cathedral"]),
    f("A flag square", ["civic square", "national plaza"]),
    f("A skyline", ["city skyline", "tall buildings"]),
    f("Tourists", ["visitors", "international tourists"]),
    f("A central station", ["main train station", "city terminal"]),
    f("A royal guard", ["ceremonial guard", "palace guards"]),
    f("A national stadium", ["state stadium", "capital arena"]),
  ]),
  q("What kind of map might you keep?", [
    f("A road map", ["driving map", "highway map"]),
    f("A subway map", ["metro map", "underground map"]),
    f("A hiking map", ["trail map", "walking map"]),
    f("A world map", ["map of the world", "global map"]),
    f("A treasure map", ["buried treasure map", "pirate map"]),
    f("A weather map", ["forecast map", "meteorological map"]),
    f("A city map", ["street map", "town map"]),
    f("A star map", ["sky map", "constellation chart"]),
    f("A topographic map", ["contour map", "terrain map"]),
    f("A political map", ["border map", "countries map"]),
    f("A land-use map", ["zoning map", "planning map"]),
    f("A nautical chart", ["sea chart", "sailing chart"]),
    f("A historical map", ["old map", "antique map"]),
    f("A geological map", ["rock map", "geology chart"]),
    f("A campus map", ["university map", "school map"]),
    f("A cycling map", ["bike map", "cycle route map"]),
  ]),
  q("Where might you spend a rainy afternoon while traveling?", [
    f("A museum", ["history museum", "indoor museum"]),
    f("A cafe", ["coffee shop", "small cafe"]),
    f("A library", ["public library", "reading library"]),
    f("A market", ["indoor market", "covered market"]),
    f("A cinema", ["movie theater", "film cinema"]),
    f("A gallery", ["art gallery", "exhibition space"]),
    f("A covered plaza", ["indoor square", "sheltered plaza"]),
    f("A train station", ["rail station", "station hall"]),
    f("A cathedral", ["historic church", "great cathedral"]),
    f("A bookshop", ["book store", "travel bookshop"]),
    f("A food hall", ["indoor food market", "market hall"]),
    f("A spa", ["day spa", "wellness center"]),
    f("A theater", ["live theater", "playhouse"]),
    f("A hotel lounge", ["lobby lounge", "hotel sitting room"]),
    f("An aquarium", ["public aquarium", "underwater museum"]),
    f("A cooking class", ["food workshop", "local cooking lesson"]),
  ]),
  q("Name a geographical feature you would photograph.", [
    f("A waterfall", ["large falls", "cascading waterfall"]),
    f("A mountain", ["high peak", "mountain summit"]),
    f("A canyon", ["deep canyon", "rock gorge"]),
    f("A glacier", ["ice glacier", "moving ice"]),
    f("A volcano", ["volcanic mountain", "active volcano"]),
    f("A river", ["wide river", "river valley"]),
    f("A desert", ["arid desert", "dry wilderness"]),
    f("A coastline", ["sea cliffs", "coastal shore"]),
    f("A cave", ["limestone cave", "underground cavern"]),
    f("A fjord", ["fjord coast", "narrow inlet"]),
    f("A delta", ["river delta", "delta wetlands"]),
    f("A reef", ["coral reef", "coastal reef"]),
    f("A geyser", ["hot spring geyser", "erupting spring"]),
    f("A dune", ["sand dune", "wind-shaped dune"]),
    f("A plateau", ["high plateau", "tableland"]),
    f("A valley", ["mountain valley", "deep valley"]),
  ]),
  q("What might you pack for a mountain trail?", [
    f("Water", ["water bottle", "drinking water"]),
    f("A map", ["trail map", "paper map"]),
    f("A jacket", ["weather jacket", "warm coat"]),
    f("Trail snacks", ["hiking food", "energy snacks"]),
    f("A first-aid kit", ["hiking medical kit", "emergency supplies"]),
    f("Hiking boots", ["trail boots", "walking boots"]),
    f("A headlamp", ["head torch", "wearable light"]),
    f("Sunglasses", ["sun glasses", "mountain shades"]),
    f("A compass", ["magnetic compass", "navigation compass"]),
    f("Walking poles", ["trekking poles", "hiking sticks"]),
    f("A whistle", ["safety whistle", "emergency whistle"]),
    f("Gloves", ["hiking gloves", "warm gloves"]),
    f("A hat", ["sun hat", "trail hat"]),
    f("A rain shell", ["waterproof jacket", "rain coat"]),
    f("A phone", ["mobile phone", "trail phone"]),
    f("A rubbish bag", ["trash bag", "pack-out bag"]),
  ]),
  q("Name a place where you might hear many languages.", [
    f("An airport", ["international airport", "airport terminal"]),
    f("A city market", ["urban market", "marketplace"]),
    f("A university", ["international university", "college campus"]),
    f("A train station", ["rail terminal", "central station"]),
    f("A border town", ["frontier town", "cross-border city"]),
    f("A hostel", ["traveler hostel", "backpacker lodge"]),
    f("A port", ["seaport", "harbor"]),
    f("A festival", ["international festival", "cultural festival"]),
    f("A tourist square", ["visitor plaza", "sightseeing square"]),
    f("A hospital", ["international hospital", "city hospital"]),
    f("A diplomatic district", ["embassy quarter", "foreign mission area"]),
    f("A shopping street", ["international shopping area", "busy shopping street"]),
    f("A conference center", ["convention center", "conference hall"]),
    f("A cruise ship", ["passenger ship", "ocean liner"]),
    f("A refugee center", ["welcome center", "resettlement center"]),
    f("A language school", ["language academy", "translation school"]),
  ]),
  q("Name a landmark found beside water.", [
    f("A lighthouse", ["coastal lighthouse", "beacon"]),
    f("A pier", ["seaside pier", "wooden pier"]),
    f("A bridge", ["river bridge", "water bridge"]),
    f("A harbor wall", ["sea wall", "breakwater wall"]),
    f("A beach promenade", ["seafront promenade", "waterfront walk"]),
    f("A canal lock", ["lock gate", "canal lock"]),
    f("A ferry terminal", ["ferry dock", "boat terminal"]),
    f("A sea fort", ["fort by the sea", "coastal fort"]),
    f("A riverfront museum", ["waterfront museum", "riverside museum"]),
    f("A marina", ["yacht harbor", "boat marina"]),
    f("A waterside statue", ["harbor statue", "water monument"]),
    f("A dam", ["river dam", "water dam"]),
    f("A beach hut", ["seaside hut", "shore hut"]),
    f("A river market", ["water market", "riverside market"]),
    f("A coastal church", ["seaside church", "shore chapel"]),
    f("A wetland boardwalk", ["marsh walkway", "wetland path"]),
  ]),
  q("What route might you take for a weekend away?", [
    f("A coastal road", ["seaside road", "coast drive"]),
    f("A forest trail", ["woodland path", "forest track"]),
    f("A rail line", ["train route", "railway journey"]),
    f("A mountain pass", ["highland pass", "alpine route"]),
    f("A river route", ["riverside road", "river journey"]),
    f("A country lane", ["rural road", "country road"]),
    f("A bike path", ["cycleway", "cycling route"]),
    f("A ferry crossing", ["ferry route", "boat crossing"]),
    f("A highway", ["motorway", "main road"]),
    f("A scenic byway", ["scenic road", "viewpoint route"]),
    f("A walking route", ["walking trail", "footpath"]),
    f("A vineyard road", ["wine route", "vineyard trail"]),
    f("A lake road", ["lakeside route", "lake drive"]),
    f("A border crossing", ["frontier route", "cross-border road"]),
    f("A canal path", ["canal towpath", "waterway walk"]),
    f("A desert track", ["desert road", "sand track"]),
  ]),
  q("Name a landscape shaped by ice.", [
    f("A glacier", ["moving ice", "ice river"]),
    f("A fjord", ["glacial inlet", "fjord valley"]),
    f("A moraine", ["glacial debris", "moraine ridge"]),
    f("An iceberg", ["floating ice", "iceberg block"]),
    f("A U-shaped valley", ["glacial valley", "U valley"]),
    f("A frozen lake", ["ice-covered lake", "winter lake"]),
    f("Permafrost", ["permanently frozen ground", "frozen soil"]),
    f("A snowfield", ["snow plain", "permanent snow"]),
    f("A drumlin", ["glacial hill", "drumlin hill"]),
    f("An esker", ["glacial ridge", "esker ridge"]),
    f("A cirque", ["glacial bowl", "mountain cirque"]),
    f("A hanging valley", ["elevated glacial valley", "hanging glacial valley"]),
    f("A kame", ["ice-contact hill", "glacial kame"]),
    f("A glacial striation", ["ice scratch", "glacier groove"]),
    f("A sea ice shelf", ["ice shelf", "polar ice shelf"]),
    f("A fjord coast", ["glacial coastline", "ice-cut coast"]),
  ]),
  q("Where might you watch the sunrise?", [
    f("A hilltop", ["top of a hill", "high viewpoint"]),
    f("A beach", ["seaside sunrise", "shoreline"]),
    f("A rooftop", ["roof terrace", "city roof"]),
    f("A desert", ["desert sunrise", "dune top"]),
    f("A harbor", ["port sunrise", "waterfront"]),
    f("A lookout", ["viewpoint", "scenic overlook"]),
    f("A train window", ["window seat", "rail journey"]),
    f("A lake shore", ["lakeside", "lake bank"]),
    f("A mountain pass", ["high pass", "alpine viewpoint"]),
    f("A balcony", ["hotel balcony", "home balcony"]),
    f("A field", ["open field", "farmland"]),
    f("A campsite", ["camp site", "tent campsite"]),
    f("A boat", ["out on the water", "boat deck"]),
    f("A temple", ["sunrise temple", "hill shrine"]),
    f("A city bridge", ["bridge viewpoint", "urban bridge"]),
    f("An airplane", ["flight window", "aircraft window"]),
  ]),
  q("Name a sign that you have crossed a border.", [
    f("A checkpoint", ["border checkpoint", "inspection point"]),
    f("A welcome sign", ["country welcome sign", "border welcome"]),
    f("A new road marker", ["different road signs", "new route marker"]),
    f("A passport stamp", ["entry stamp", "immigration stamp"]),
    f("A flag", ["national flag", "country flag"]),
    f("A change in language", ["new language", "different words"]),
    f("A customs booth", ["customs checkpoint", "border customs"]),
    f("A border fence", ["frontier fence", "boundary fence"]),
    f("A currency change", ["new currency", "different money"]),
    f("A speed-limit change", ["new speed signs", "different speed limit"]),
    f("A toll gate", ["border toll", "road toll"]),
    f("A police post", ["border police", "frontier police"]),
    f("A new time zone", ["clock change", "time-zone shift"]),
    f("A visa check", ["document inspection", "visa control"]),
    f("A change in road side", ["drive on the other side", "traffic-side change"]),
    f("A different landscape", ["new scenery", "changed terrain"]),
  ]),
  q("What might you find at a local market while traveling?", [
    f("Spices", ["local spices", "seasoning stalls"]),
    f("Fruit", ["fresh fruit", "market fruit"]),
    f("Handicrafts", ["local crafts", "handmade goods"]),
    f("Street food", ["market food", "food stalls"]),
    f("Flowers", ["market flowers", "flower stalls"]),
    f("Textiles", ["woven cloth", "local fabrics"]),
    f("Fresh fish", ["market fish", "seafood stall"]),
    f("Postcards", ["travel cards", "picture postcards"]),
    f("Cheese", ["local cheese", "cheese stall"]),
    f("Bread", ["fresh bread", "market loaves"]),
    f("Pottery", ["ceramics", "clay goods"]),
    f("Jewelry", ["jewellery", "market jewelry"]),
    f("Coffee", ["local coffee", "coffee beans"]),
    f("Meat", ["butcher stall", "market meat"]),
    f("Honey", ["local honey", "honey jars"]),
    f("Souvenirs", ["travel souvenirs", "keepsakes"]),
  ]),
  q("Where might you go to stargaze?", [
    f("A dark-sky park", ["dark sky reserve", "stargazing park"]),
    f("A hilltop", ["high hill", "hill viewpoint"]),
    f("A desert", ["desert night", "open desert"]),
    f("A rooftop", ["roof observatory", "city rooftop"]),
    f("An observatory", ["star observatory", "astronomy center"]),
    f("A campsite", ["camping ground", "tent site"]),
    f("A beach", ["seaside night", "shoreline sky"]),
    f("A field", ["open field", "farmland sky"]),
    f("A mountain cabin", ["remote cabin", "highland cabin"]),
    f("A planetarium", ["star theater", "astronomy dome"]),
    f("A national park", ["park wilderness", "protected park"]),
    f("A boat deck", ["ship deck", "out at sea"]),
    f("A balcony", ["night balcony", "apartment balcony"]),
    f("A remote island", ["island night", "far island"]),
    f("A monastery", ["quiet monastery", "hill monastery"]),
    f("A railway platform", ["station platform", "train platform"]),
  ]),
  q("Name a type of border.", [
    f("A national border", ["country boundary", "state frontier"]),
    f("A river border", ["water boundary", "river frontier"]),
    f("A mountain border", ["alpine boundary", "mountain frontier"]),
    f("A sea border", ["maritime boundary", "ocean border"]),
    f("A cultural border", ["cultural divide", "culture boundary"]),
    f("A language border", ["linguistic boundary", "language divide"]),
    f("A political border", ["political boundary", "government frontier"]),
    f("A forest border", ["woodland boundary", "tree-line border"]),
    f("A city limit", ["town boundary", "municipal border"]),
    f("A time-zone border", ["time boundary", "clock border"]),
    f("A climate border", ["climate boundary", "weather divide"]),
    f("A farm boundary", ["field boundary", "property line"]),
    f("A state line", ["regional boundary", "state border"]),
    f("A customs border", ["customs boundary", "trade frontier"]),
    f("A continental divide", ["watershed divide", "continent boundary"]),
    f("A digital border", ["online boundary", "internet border"]),
  ]),
  q("What might you see in an old town?", [
    f("Narrow streets", ["old lanes", "small historic streets"]),
    f("A stone church", ["historic church", "old chapel"]),
    f("A market square", ["town square", "historic plaza"]),
    f("City walls", ["old walls", "town fortifications"]),
    f("A clock tower", ["town clock", "historic tower"]),
    f("Cobblestones", ["cobbled streets", "stone paving"]),
    f("A fountain", ["old fountain", "town fountain"]),
    f("A town hall", ["historic town hall", "civic hall"]),
    f("A castle", ["old castle", "fortified castle"]),
    f("Wooden houses", ["timber houses", "old houses"]),
    f("An archway", ["old arch", "stone archway"]),
    f("A bakery", ["old bakery", "town bread shop"]),
    f("A bridge", ["old bridge", "stone bridge"]),
    f("A statue", ["historic statue", "town monument"]),
    f("A courtyard", ["old courtyard", "inner square"]),
    f("A museum", ["local museum", "heritage museum"]),
  ]),
  q("Name a destination near a river.", [
    f("A riverside city", ["river city", "city by a river"]),
    f("A delta", ["river delta", "delta town"]),
    f("A river village", ["riverside village", "village by water"]),
    f("A valley", ["river valley", "valley settlement"]),
    f("A floodplain", ["river plain", "flood meadow"]),
    f("A river island", ["island in the river", "river isle"]),
    f("A riverside park", ["river park", "waterfront park"]),
    f("A ferry town", ["river crossing town", "ferry village"]),
    f("A canyon", ["river canyon", "gorge by water"]),
    f("A waterfall", ["river falls", "waterfall destination"]),
    f("A wetland", ["river wetlands", "marsh beside a river"]),
    f("A port", ["river port", "inland harbor"]),
    f("A hot spring", ["river hot spring", "thermal river"]),
    f("A vineyard", ["river vineyard", "wine valley"]),
    f("A bridge town", ["town at a bridge", "river bridge town"]),
    f("A reservoir", ["river reservoir", "dam lake"]),
  ]),
  q("Name a route through mountains.", [
    f("A mountain pass", ["high pass", "alpine pass"]),
    f("A tunnel", ["mountain tunnel", "road tunnel"]),
    f("A switchback road", ["hairpin road", "zigzag road"]),
    f("A valley road", ["mountain valley route", "road through a valley"]),
    f("A cable car", ["gondola lift", "mountain cableway"]),
    f("A hiking trail", ["mountain trail", "walking route"]),
    f("A railway", ["mountain railway", "rail route"]),
    f("A river gorge", ["gorge route", "river canyon path"]),
    f("A ridge path", ["mountain ridge trail", "ridge route"]),
    f("A ski lift", ["chairlift", "mountain lift"]),
    f("A border road", ["frontier mountain road", "highland border route"]),
    f("A mule track", ["pack trail", "old mountain path"]),
    f("A scenic drive", ["mountain scenic road", "viewpoint drive"]),
    f("A glacier route", ["ice crossing", "glacier path"]),
    f("A pilgrim trail", ["pilgrimage route", "mountain pilgrimage"]),
    f("A river crossing", ["mountain ford", "stream crossing"]),
  ]),
  q("Name a place with an extreme climate.", [
    f("The Arctic", ["polar north", "far northern ice"]),
    f("The Sahara", ["Sahara Desert", "hot desert"]),
    f("Antarctica", ["the Antarctic", "polar continent"]),
    f("A tropical rainforest", ["equatorial forest", "humid jungle"]),
    f("A high plateau", ["high-altitude plateau", "mountain tableland"]),
    f("A monsoon coast", ["monsoon region", "seasonal rain coast"]),
    f("A salt flat", ["salt desert", "dry salt plain"]),
    f("A volcano island", ["volcanic island", "active volcano coast"]),
    f("A tundra", ["treeless tundra", "frozen plain"]),
    f("A dry valley", ["rain-shadow valley", "arid valley"]),
    f("A cyclone coast", ["hurricane coast", "storm-prone shore"]),
    f("A glacier field", ["ice sheet", "permanent ice"]),
    f("A mangrove swamp", ["tropical wetland", "mangrove coast"]),
    f("A steppe", ["dry grassland", "continental steppe"]),
    f("A hot spring basin", ["geothermal basin", "thermal landscape"]),
    f("A fog coast", ["misty coastline", "fog belt"]),
  ]),
  q("What might be at a train station?", [
    f("Platforms", ["train platforms", "rail platforms"]),
    f("A ticket office", ["ticket counter", "station ticket desk"]),
    f("Timetables", ["train schedules", "departure board"]),
    f("A waiting room", ["station lounge", "passenger waiting area"]),
    f("Tracks", ["rail tracks", "train lines"]),
    f("A signal", ["rail signal", "train signal"]),
    f("A station clock", ["platform clock", "railway clock"]),
    f("A cafe", ["station cafe", "rail cafe"]),
    f("A luggage locker", ["left luggage", "station lockers"]),
    f("A conductor", ["train conductor", "rail worker"]),
    f("A footbridge", ["platform bridge", "station footbridge"]),
    f("A train", ["passenger train", "railway train"]),
    f("A kiosk", ["news kiosk", "station shop"]),
    f("A loudspeaker", ["station announcement", "public address speaker"]),
    f("A barrier", ["ticket barrier", "station gate"]),
    f("A map", ["rail map", "station map"]),
  ]),
  q("Name an item a traveler carries.", [
    f("A passport", ["travel document", "passport booklet"]),
    f("A suitcase", ["travel case", "luggage"]),
    f("A backpack", ["travel pack", "carry bag"]),
    f("A map", ["travel map", "route map"]),
    f("A camera", ["travel camera", "photo camera"]),
    f("A water bottle", ["drinking bottle", "travel bottle"]),
    f("A phone", ["mobile phone", "travel phone"]),
    f("A wallet", ["money wallet", "purse"]),
    f("A guidebook", ["travel guide", "city guide"]),
    f("A ticket", ["travel ticket", "boarding ticket"]),
    f("Sunglasses", ["sun glasses", "travel shades"]),
    f("A charger", ["travel charger", "charging cable"]),
    f("A jacket", ["travel coat", "light jacket"]),
    f("Snacks", ["travel food", "journey snacks"]),
    f("A toiletry bag", ["wash bag", "travel toiletries"]),
    f("A notebook", ["travel journal", "trip notebook"]),
  ]),
  q("Name a sign of coastal erosion.", [
    f("A collapsing cliff", ["eroding cliff", "falling sea cliff"]),
    f("A shrinking beach", ["narrower beach", "lost sand"]),
    f("Exposed roots", ["tree roots showing", "uncovered roots"]),
    f("A damaged seawall", ["broken sea wall", "eroded seawall"]),
    f("Fallen rocks", ["rockfall", "collapsed rocks"]),
    f("Undercut dunes", ["eroded sand dunes", "dune scarp"]),
    f("A relocated road", ["moved coastal road", "retreated road"]),
    f("Debris on the shore", ["shore debris", "washed-up rubble"]),
    f("Exposed fossils", ["fossils in the cliff", "revealed fossils"]),
    f("A sea cave", ["eroded sea cave", "coastal cave"]),
    f("A narrow spit", ["eroded sand spit", "thin coastal spit"]),
    f("Flooded paths", ["washed paths", "flooded coastal trail"]),
    f("Beach scarp", ["sand cliff", "shore scarp"]),
    f("Missing vegetation", ["lost coastal plants", "bare dunes"]),
    f("Waves reaching buildings", ["sea at houses", "waves near homes"]),
    f("A retreating shoreline", ["shoreline retreat", "coast moving inland"]),
  ]),
  q("Where might you go to see wildlife?", [
    f("A national park", ["protected park", "wildlife park"]),
    f("A safari reserve", ["game reserve", "safari park"]),
    f("A rainforest", ["jungle", "tropical forest"]),
    f("A wetland", ["marsh", "wildlife wetland"]),
    f("A coral reef", ["reef habitat", "underwater reef"]),
    f("A desert", ["desert habitat", "arid wilderness"]),
    f("A mountain range", ["mountain wilderness", "highland habitat"]),
    f("A bird sanctuary", ["bird reserve", "avian sanctuary"]),
    f("A river", ["river habitat", "riverside wildlife"]),
    f("A forest", ["woodland", "forest habitat"]),
    f("A coastal reserve", ["marine reserve", "protected coast"]),
    f("A wildlife corridor", ["animal corridor", "nature passage"]),
    f("A tide pool", ["rock pool", "shore pool"]),
    f("A nature trail", ["wildlife trail", "observation path"]),
    f("An island", ["wildlife island", "remote island"]),
    f("A zoo", ["animal park", "zoological garden"]),
  ]),
  q("Name a feature of a city skyline.", [
    f("Skyscrapers", ["tall towers", "high-rise buildings"]),
    f("A radio tower", ["broadcast tower", "communications tower"]),
    f("A dome", ["city dome", "domed building"]),
    f("A church spire", ["cathedral spire", "steeple"]),
    f("A bridge", ["skyline bridge", "city bridge"]),
    f("A Ferris wheel", ["observation wheel", "giant wheel"]),
    f("A crane", ["construction crane", "building crane"]),
    f("A stadium", ["sports stadium", "city arena"]),
    f("A water tower", ["city water tower", "elevated tank"]),
    f("A mountain backdrop", ["hills behind the city", "city mountains"]),
    f("A clock tower", ["city clock", "tower landmark"]),
    f("A glass tower", ["glass skyscraper", "reflective tower"]),
    f("A smokestack", ["factory chimney", "industrial stack"]),
    f("A monument", ["city monument", "national landmark"]),
    f("A lighthouse", ["urban lighthouse", "harbor beacon"]),
    f("A rooftop garden", ["green roof", "sky garden"]),
  ]),
  q("What might you find on an island?", [
    f("A beach", ["island beach", "sandy shore"]),
    f("A volcano", ["island volcano", "volcanic peak"]),
    f("Palm trees", ["tropical palms", "palm forest"]),
    f("A fishing village", ["island village", "coastal village"]),
    f("A lighthouse", ["island beacon", "coastal light"]),
    f("A reef", ["island coral reef", "surrounding reef"]),
    f("A harbor", ["island harbor", "small port"]),
    f("A ferry dock", ["island ferry terminal", "boat dock"]),
    f("Sea birds", ["island birds", "coastal birds"]),
    f("A cave", ["island cave", "sea cavern"]),
    f("A lagoon", ["island lagoon", "blue lagoon"]),
    f("A jungle", ["island rainforest", "tropical forest"]),
    f("A salt marsh", ["coastal marsh", "island wetland"]),
    f("A resort", ["island resort", "holiday resort"]),
    f("A temple", ["island shrine", "island temple"]),
    f("A cliff", ["sea cliff", "island cliffs"]),
  ]),
  q("How might a map show elevation?", [
    f("Contour lines", ["elevation lines", "contour map lines"]),
    f("Color shading", ["height colors", "elevation colors"]),
    f("Spot heights", ["height points", "elevation points"]),
    f("Hill symbols", ["mountain symbols", "terrain icons"]),
    f("A topographic profile", ["terrain cross-section", "elevation profile"]),
    f("Relief shading", ["hillshade", "shadow relief"]),
    f("Benchmarks", ["survey benchmarks", "fixed height marks"]),
    f("A scale", ["height scale", "elevation legend"]),
    f("A summit label", ["peak height", "mountain elevation label"]),
    f("A digital terrain model", ["terrain model", "elevation model"]),
    f("A 3D surface", ["three-dimensional terrain", "3D relief"]),
    f("Gradient tints", ["hypsometric tints", "height color bands"]),
    f("A sea-level datum", ["reference sea level", "vertical datum"]),
    f("A hill profile", ["ridge profile", "slope profile"]),
    f("A relief map", ["raised relief map", "terrain relief"]),
    f("Altitude labels", ["height labels", "elevation numbers"]),
  ]),
  q("Where might people cross water?", [
    f("A bridge", ["water bridge", "crossing bridge"]),
    f("A ferry", ["ferry boat", "water ferry"]),
    f("A ford", ["river ford", "shallow crossing"]),
    f("A tunnel", ["underwater tunnel", "water tunnel"]),
    f("A footbridge", ["pedestrian bridge", "walking bridge"]),
    f("A dam", ["dam crossing", "reservoir dam"]),
    f("A stepping-stone path", ["stepping stones", "stone crossing"]),
    f("A boat", ["small boat crossing", "rowboat"]),
    f("A causeway", ["water causeway", "raised road"]),
    f("A raft", ["floating raft", "raft crossing"]),
    f("A cable ferry", ["cable boat", "chain ferry"]),
    f("A boardwalk", ["wetland boardwalk", "raised walkway"]),
    f("A weir", ["weir crossing", "low water crossing"]),
    f("A zipline", ["water zipline", "cable ride"]),
    f("A water taxi", ["river taxi", "boat taxi"]),
    f("A tidal bridge", ["coastal crossing", "sea bridge"]),
  ]),
  q("Where might you look for local food?", [
    f("A street market", ["food market", "market stalls"]),
    f("A family restaurant", ["local restaurant", "neighborhood eatery"]),
    f("A food hall", ["market hall", "indoor food market"]),
    f("A bakery", ["local bakery", "bread shop"]),
    f("A farm shop", ["farm store", "farmers' shop"]),
    f("A fish market", ["seafood market", "fish stall"]),
    f("A food truck", ["street food truck", "mobile kitchen"]),
    f("A village cafe", ["local cafe", "small cafe"]),
    f("A vineyard", ["wine estate", "local winery"]),
    f("A cheese shop", ["cheese store", "local cheese shop"]),
    f("A spice bazaar", ["spice market", "seasoning bazaar"]),
    f("A tea house", ["local tea room", "tea shop"]),
    f("A cooking school", ["food class", "local cooking lesson"]),
    f("A deli", ["local deli", "delicatessen"]),
    f("A harbor stall", ["seaside food stall", "port food stand"]),
    f("A home kitchen", ["household cooking", "home meal"]),
  ]),
];
