import { family as f, question as q } from "./common.mjs";

export const history = [
  q("Name an object that belongs in a museum.", [
    f("A sword", ["old sword", "historic blade"]),
    f("A painting", ["old painting", "historic artwork"]),
    f("A fossil", ["ancient fossil", "fossil specimen"]),
    f("A letter", ["historic letter", "old correspondence"]),
    f("A coin", ["old coin", "historic currency"]),
    f("A statue", ["historic statue", "sculpture"]),
    f("A photograph", ["old photograph", "historic photo"]),
    f("A suit of armor", ["armor suit", "knight armor"]),
    f("A pottery shard", ["ceramic fragment", "broken pottery"]),
    f("A royal crown", ["king's crown", "monarch crown"]),
    f("A map", ["historic map", "old map"]),
    f("A tool", ["ancient tool", "historic implement"]),
    f("A uniform", ["historic uniform", "old military clothing"]),
    f("A diary", ["historic diary", "personal journal"]),
    f("A manuscript", ["old manuscript", "handwritten text"]),
    f("A ship model", ["model vessel", "historic ship model"]),
  ]),
  q("What can make an old city memorable?", [
    f("A fortress", ["old fort", "city fortress"]),
    f("Narrow streets", ["historic lanes", "old streets"]),
    f("A cathedral", ["historic cathedral", "great church"]),
    f("Ruins", ["ancient ruins", "city remains"]),
    f("A market square", ["old market", "historic plaza"]),
    f("Old bridges", ["historic bridges", "stone bridges"]),
    f("City walls", ["ancient walls", "town walls"]),
    f("A palace", ["old palace", "royal residence"]),
    f("A clock tower", ["historic clock", "town tower"]),
    f("Cobblestones", ["cobbled lanes", "stone paving"]),
    f("A town hall", ["historic town hall", "civic building"]),
    f("A monument", ["city monument", "historic memorial"]),
    f("A harbor", ["old harbor", "historic port"]),
    f("A castle", ["city castle", "old castle"]),
    f("A fountain", ["historic fountain", "old fountain"]),
    f("An old theater", ["historic theater", "heritage playhouse"]),
  ]),
  q("Why do people write things down for future generations?", [
    f("To record events", ["document events", "keep a record"]),
    f("To preserve stories", ["save stories", "keep memories"]),
    f("To make laws", ["write laws", "record rules"]),
    f("To share knowledge", ["pass on knowledge", "teach information"]),
    f("To keep accounts", ["record finances", "track accounts"]),
    f("To remember people", ["honor people", "keep names"]),
    f("To teach", ["educate others", "leave lessons"]),
    f("To leave a warning", ["record a warning", "warn descendants"]),
    f("To mark ownership", ["record property", "claim land"]),
    f("To preserve language", ["save words", "record a language"]),
    f("To explain beliefs", ["write beliefs", "preserve faith"]),
    f("To pass on recipes", ["save recipes", "keep cooking knowledge"]),
    f("To describe places", ["record geography", "describe a land"]),
    f("To prove an agreement", ["write a contract", "record a pact"]),
    f("To leave a diary", ["keep a journal", "write personal history"]),
    f("To celebrate a victory", ["record triumph", "honor success"]),
  ]),
  q("What might an explorer pack?", [
    f("A compass", ["magnetic compass", "navigation compass"]),
    f("A map", ["exploration map", "route map"]),
    f("Rope", ["climbing rope", "strong rope"]),
    f("Food", ["travel provisions", "packed food"]),
    f("A journal", ["explorer diary", "field journal"]),
    f("Warm clothing", ["extra clothes", "cold-weather gear"]),
    f("A camera", ["explorer camera", "photography gear"]),
    f("A lantern", ["travel lantern", "oil lamp"]),
    f("A water flask", ["canteen", "water container"]),
    f("A knife", ["field knife", "survival blade"]),
    f("A telescope", ["spyglass", "small telescope"]),
    f("A first-aid kit", ["medical supplies", "expedition kit"]),
    f("A notebook", ["field notebook", "travel notes"]),
    f("A tent", ["camping tent", "shelter tent"]),
    f("A sextant", ["navigation sextant", "sea instrument"]),
    f("Trade goods", ["trading supplies", "exchange goods"]),
  ]),
  q("Name a symbol of a revolution.", [
    f("A flag", ["revolutionary flag", "banner"]),
    f("A raised fist", ["clenched fist", "revolution fist"]),
    f("A barricade", ["street barricade", "revolution barricade"]),
    f("A pamphlet", ["political pamphlet", "revolution leaflet"]),
    f("A torch", ["revolution torch", "burning torch"]),
    f("A broken chain", ["shattered chain", "broken shackles"]),
    f("A marching crowd", ["protest march", "revolutionary crowd"]),
    f("A red star", ["revolution star", "red emblem"]),
    f("A slogan", ["revolutionary slogan", "political motto"]),
    f("A street poster", ["protest poster", "revolution poster"]),
    f("A rifle", ["revolutionary rifle", "insurgent weapon"]),
    f("A red scarf", ["revolution scarf", "red neckerchief"]),
    f("A constitution", ["new constitution", "revolutionary charter"]),
    f("A guillotine", ["revolution guillotine", "execution machine"]),
    f("A newspaper", ["revolution newspaper", "political paper"]),
    f("A song", ["revolution song", "protest song"]),
  ]),
  q("What would you find in a medieval market?", [
    f("Spices", ["market spices", "exotic seasoning"]),
    f("Cloth", ["market fabric", "woven cloth"]),
    f("Bread", ["market bread", "fresh loaf"]),
    f("Blacksmiths", ["smiths", "blacksmith stalls"]),
    f("Horses", ["market horses", "trade horses"]),
    f("Pottery", ["market ceramics", "clay pots"]),
    f("Ale", ["medieval beer", "market ale"]),
    f("Travelers", ["passing travelers", "merchants and travelers"]),
    f("Herbs", ["healing herbs", "market herbs"]),
    f("Leather", ["leather goods", "tanned leather"]),
    f("Fish", ["market fish", "fresh fish"]),
    f("Grain", ["wheat grain", "market grain"]),
    f("Candles", ["market candles", "tallow candles"]),
    f("Coins", ["market coins", "trading money"]),
    f("Baskets", ["woven baskets", "market baskets"]),
    f("A tanner", ["leather worker", "tanning stall"]),
  ]),
  q("Name a historical era you would visit.", [
    f("Ancient Rome", ["Roman era", "Roman Empire"]),
    f("The Renaissance", ["Renaissance period", "rebirth era"]),
    f("The Viking Age", ["Viking era", "Norse age"]),
    f("The Jazz Age", ["Roaring Twenties", "jazz era"]),
    f("The Victorian era", ["Victorian period", "Queen Victoria's era"]),
    f("The Space Race", ["space-race era", "moon race"]),
    f("The Silk Road era", ["Silk Road period", "caravan age"]),
    f("The 1960s", ["sixties", "1960s decade"]),
    f("Ancient Egypt", ["Egyptian antiquity", "pharaoh era"]),
    f("Classical Greece", ["Ancient Greece", "Greek classical age"]),
    f("The Middle Ages", ["medieval period", "medieval era"]),
    f("The Industrial Revolution", ["industrial age", "machine age"]),
    f("The Enlightenment", ["Age of Reason", "Enlightenment period"]),
    f("The Bronze Age", ["Bronze Age period", "early metal age"]),
    f("The Cold War", ["Cold War period", "East-West conflict era"]),
    f("The 1920s", ["twenties", "1920s decade"]),
  ]),
  q("What survives from an ancient civilization?", [
    f("Ruins", ["ancient remains", "collapsed structures"]),
    f("Pottery", ["ancient ceramics", "old pots"]),
    f("Writing", ["ancient scripts", "old writing"]),
    f("Roads", ["ancient roads", "old roadways"]),
    f("Myths", ["ancient myths", "old legends"]),
    f("Tools", ["ancient tools", "old implements"]),
    f("Jewelry", ["ancient jewelry", "old ornaments"]),
    f("Buildings", ["ancient buildings", "old structures"]),
    f("Coins", ["ancient coins", "old currency"]),
    f("Sculptures", ["ancient statues", "stone sculptures"]),
    f("Tombs", ["ancient graves", "burial tombs"]),
    f("Seeds", ["ancient seeds", "old crop seeds"]),
    f("Weapons", ["ancient weapons", "old arms"]),
    f("Inscriptions", ["stone inscriptions", "carved writing"]),
    f("Shipwrecks", ["ancient wrecks", "sunken ships"]),
    f("Burial sites", ["ancient gravesites", "archaeological burials"]),
  ]),
  q("Name a monument people visit to remember history.", [
    f("A memorial", ["war memorial", "commemorative memorial"]),
    f("A statue", ["historic statue", "commemorative statue"]),
    f("A battlefield", ["historic battlefield", "battle site"]),
    f("A tomb", ["historic tomb", "burial monument"]),
    f("A monument arch", ["triumphal arch", "memorial arch"]),
    f("A museum", ["history museum", "memorial museum"]),
    f("A historic house", ["heritage home", "historic residence"]),
    f("A wall", ["historic wall", "memorial wall"]),
    f("A cemetery", ["historic cemetery", "memorial graveyard"]),
    f("A plaque", ["memorial plaque", "commemorative plaque"]),
    f("A monument column", ["memorial column", "stone column"]),
    f("A shrine", ["historic shrine", "memorial shrine"]),
    f("A ruined city", ["ancient city ruins", "ruined settlement"]),
    f("A battlefield cross", ["war cross", "battle memorial cross"]),
    f("A liberty bell", ["freedom bell", "historic bell"]),
    f("A remembrance garden", ["memorial garden", "memory garden"]),
  ]),
  q("What might appear in a family archive?", [
    f("Photographs", ["family photos", "old pictures"]),
    f("Letters", ["family letters", "old correspondence"]),
    f("Birth records", ["birth certificates", "birth documents"]),
    f("A diary", ["family diary", "personal journal"]),
    f("A recipe", ["family recipe", "old recipe"]),
    f("Postcards", ["family postcards", "travel cards"]),
    f("A military medal", ["service medal", "war medal"]),
    f("Newspaper clippings", ["press clippings", "old newspaper articles"]),
    f("A marriage certificate", ["wedding record", "marriage document"]),
    f("A school report", ["school record", "old report card"]),
    f("A family tree", ["genealogy chart", "ancestry tree"]),
    f("A will", ["last will", "inheritance document"]),
    f("A land deed", ["property deed", "old deed"]),
    f("A passport", ["old passport", "travel document"]),
    f("A funeral card", ["memorial card", "mourning card"]),
    f("A voice recording", ["family audio", "old recording"]),
  ]),
  q("Name a job in a historic town.", [
    f("A blacksmith", ["town smith", "forge worker"]),
    f("A merchant", ["market trader", "town seller"]),
    f("A printer", ["printing worker", "press operator"]),
    f("A baker", ["town baker", "bread maker"]),
    f("A guide", ["history guide", "tour guide"]),
    f("A farmer", ["town farmer", "field worker"]),
    f("A shipwright", ["ship builder", "boat builder"]),
    f("A scribe", ["copyist", "writing clerk"]),
    f("A weaver", ["cloth maker", "loom worker"]),
    f("A potter", ["ceramic maker", "clay worker"]),
    f("A cooper", ["barrel maker", "cask maker"]),
    f("A stable keeper", ["stable worker", "horse keeper"]),
    f("A miller", ["grain miller", "mill worker"]),
    f("An apothecary", ["medieval pharmacist", "herbal healer"]),
    f("A tanner", ["leather worker", "hide tanner"]),
    f("A ferryman", ["river ferryman", "boatman"]),
  ]),
  q("Why might a kingdom be remembered?", [
    f("Its rulers", ["kings and queens", "royal leaders"]),
    f("A great battle", ["famous war", "historic battle"]),
    f("Its art", ["kingdom artwork", "royal art"]),
    f("Its inventions", ["kingdom innovations", "old inventions"]),
    f("A law code", ["written laws", "royal code"]),
    f("Its buildings", ["royal buildings", "kingdom architecture"]),
    f("Its trade", ["kingdom commerce", "trade routes"]),
    f("A rebellion", ["kingdom revolt", "uprising"]),
    f("Its religion", ["royal religion", "kingdom faith"]),
    f("Its language", ["kingdom language", "historic tongue"]),
    f("A royal marriage", ["dynastic marriage", "kingdom wedding"]),
    f("Its collapse", ["fall of the kingdom", "kingdom downfall"]),
    f("Its colonies", ["overseas territories", "kingdom colonies"]),
    f("Its explorers", ["royal explorers", "kingdom voyages"]),
    f("Its music", ["court music", "royal songs"]),
    f("Its stories", ["kingdom legends", "royal tales"]),
  ]),
  q("What might you see in a portrait from the early twentieth century?", [
    f("Formal clothing", ["smart clothes", "formal dress"]),
    f("A studio backdrop", ["portrait background", "painted backdrop"]),
    f("A hat", ["formal hat", "period hat"]),
    f("A uniform", ["service uniform", "period uniform"]),
    f("A family group", ["family portrait", "group portrait"]),
    f("A serious pose", ["formal pose", "solemn expression"]),
    f("A pocket watch", ["watch chain", "period watch"]),
    f("A painted photograph", ["tinted photograph", "hand-colored photo"]),
    f("A lace collar", ["lace clothing", "high collar"]),
    f("A waistcoat", ["vest", "formal waistcoat"]),
    f("A mustache", ["period mustache", "facial hair"]),
    f("A studio chair", ["portrait chair", "photography chair"]),
    f("A brooch", ["period brooch", "ornamental pin"]),
    f("A rural backdrop", ["painted landscape backdrop", "country background"]),
    f("A handwritten name", ["portrait inscription", "written name"]),
    f("A stiff collar", ["starched collar", "high shirt collar"]),
  ]),
  q("Name an object in a space-race exhibit.", [
    f("A rocket", ["launch vehicle", "space rocket"]),
    f("A spacesuit", ["space suit", "astronaut suit"]),
    f("A capsule", ["space capsule", "crew capsule"]),
    f("A moon rock", ["lunar rock", "moon sample"]),
    f("A mission patch", ["space patch", "mission emblem"]),
    f("A launch plan", ["flight plan", "mission plan"]),
    f("A satellite", ["orbiting satellite", "space satellite"]),
    f("A control panel", ["flight panel", "command console"]),
    f("A lunar rover", ["moon rover", "space rover"]),
    f("An astronaut helmet", ["space helmet", "flight helmet"]),
    f("A reentry shield", ["heat shield", "capsule shield"]),
    f("A countdown clock", ["launch timer", "mission clock"]),
    f("A flight computer", ["guidance computer", "onboard computer"]),
    f("A radio antenna", ["space antenna", "mission antenna"]),
    f("A star chart", ["navigation chart", "space map"]),
    f("A mission photograph", ["space photo", "flight photograph"]),
  ]),
  q("Name an ingredient that might survive in an old recipe.", [
    f("Salt", ["table salt", "sea salt"]),
    f("Honey", ["raw honey", "sweet honey"]),
    f("Onions", ["cooking onions", "bulb onions"]),
    f("Wheat", ["wheat flour", "grain wheat"]),
    f("Beans", ["dried beans", "cooking beans"]),
    f("Apples", ["cooking apples", "old orchard apples"]),
    f("Cinnamon", ["cinnamon spice", "ground cinnamon"]),
    f("Vinegar", ["cider vinegar", "sour vinegar"]),
    f("Herbs", ["dried herbs", "cooking herbs"]),
    f("Garlic", ["garlic cloves", "kitchen garlic"]),
    f("Lard", ["cooking fat", "pork fat"]),
    f("Barley", ["barley grain", "pearl barley"]),
    f("Pepper", ["black pepper", "peppercorn"]),
    f("Milk", ["fresh milk", "cow milk"]),
    f("Raisins", ["dried grapes", "sultanas"]),
    f("Mustard", ["mustard seed", "prepared mustard"]),
  ]),
  q("Name an invention people use every day.", [
    f("The telephone", ["phone", "telephone device"]),
    f("The light bulb", ["electric bulb", "lamp bulb"]),
    f("The wheel", ["rolling wheel", "cart wheel"]),
    f("The printing press", ["print press", "movable type press"]),
    f("The refrigerator", ["fridge", "cold storage"]),
    f("The zipper", ["zip fastener", "clothing zipper"]),
    f("The computer", ["personal computer", "desktop computer"]),
    f("The internet", ["world wide web", "online network"]),
    f("The battery", ["electric cell", "power battery"]),
    f("The bicycle", ["bike", "pedal cycle"]),
    f("The elevator", ["lift", "passenger lift"]),
    f("The washing machine", ["clothes washer", "laundry machine"]),
    f("The microwave", ["microwave oven", "kitchen microwave"]),
    f("The radio", ["wireless radio", "radio receiver"]),
    f("The camera", ["photo camera", "image camera"]),
    f("The train", ["railway train", "steam train"]),
  ]),
  q("Name an object from ancient Egypt.", [
    f("A pyramid", ["Egyptian pyramid", "stone pyramid"]),
    f("A mummy", ["mummified body", "Egyptian mummy"]),
    f("A sarcophagus", ["stone coffin", "Egyptian coffin"]),
    f("A hieroglyph", ["Egyptian writing", "hieroglyphic sign"]),
    f("A scarab", ["scarab beetle", "Egyptian scarab"]),
    f("A pharaoh's crown", ["royal headdress", "pharaoh crown"]),
    f("A papyrus", ["papyrus scroll", "Egyptian papyrus"]),
    f("A canopic jar", ["mummy jar", "canopic vessel"]),
    f("A gold mask", ["funerary mask", "Egyptian gold mask"]),
    f("A temple column", ["Egyptian column", "temple pillar"]),
    f("A burial amulet", ["Egyptian amulet", "protective charm"]),
    f("A chariot", ["Egyptian chariot", "horse chariot"]),
    f("A reed pen", ["papyrus pen", "ancient pen"]),
    f("A linen robe", ["Egyptian linen", "linen clothing"]),
    f("A model boat", ["funerary boat", "Egyptian boat model"]),
    f("A royal seal", ["scarab seal", "pharaoh seal"]),
  ]),
  q("Name an event people remember from history.", [
    f("A revolution", ["historic revolution", "political uprising"]),
    f("A coronation", ["royal coronation", "crowning ceremony"]),
    f("A great battle", ["historic battle", "major conflict"]),
    f("A discovery", ["historic discovery", "important finding"]),
    f("A migration", ["mass migration", "people moving"]),
    f("A treaty", ["peace treaty", "historic agreement"]),
    f("An election", ["historic election", "national vote"]),
    f("A disaster", ["historic disaster", "major catastrophe"]),
    f("A scientific breakthrough", ["major discovery", "science breakthrough"]),
    f("A protest", ["historic protest", "mass demonstration"]),
    f("A royal wedding", ["dynastic wedding", "kingdom marriage"]),
    f("A flight", ["first flight", "historic aviation"]),
    f("A landing", ["historic landing", "arrival event"]),
    f("An independence day", ["independence declaration", "national independence"]),
    f("A pandemic", ["historic epidemic", "global outbreak"]),
    f("A peace accord", ["peace agreement", "historic peace deal"]),
  ]),
  q("Name something kept in a historical archive.", [
    f("A manuscript", ["archival manuscript", "old handwritten text"]),
    f("A newspaper", ["old newspaper", "archived paper"]),
    f("A photograph", ["archival photo", "historic photograph"]),
    f("A map", ["archival map", "old map"]),
    f("A government record", ["state document", "official record"]),
    f("A census", ["population census", "census record"]),
    f("A diary", ["archived diary", "personal journal"]),
    f("A letter", ["archived letter", "historical correspondence"]),
    f("A recording", ["archival audio", "old recording"]),
    f("A film reel", ["archived film", "movie reel"]),
    f("A legal deed", ["property deed", "archival deed"]),
    f("A parish register", ["church register", "parish record"]),
    f("A treaty", ["archived treaty", "signed agreement"]),
    f("A blueprint", ["historic plan", "architectural blueprint"]),
    f("A poster", ["archival poster", "historic poster"]),
    f("A ledger", ["account ledger", "old accounts book"]),
  ]),
  q("Name a role in a medieval town.", [
    f("A mayor", ["town mayor", "city reeve"]),
    f("A guild master", ["guild leader", "master craftsman"]),
    f("A merchant", ["town trader", "market merchant"]),
    f("A guard", ["town guard", "city watchman"]),
    f("A priest", ["parish priest", "town cleric"]),
    f("A midwife", ["birth helper", "town midwife"]),
    f("A blacksmith", ["forge worker", "town smith"]),
    f("A farmer", ["village farmer", "field worker"]),
    f("A baker", ["town baker", "bread maker"]),
    f("A scribe", ["writing clerk", "town copyist"]),
    f("A miller", ["grain miller", "watermill worker"]),
    f("A mason", ["stone mason", "building worker"]),
    f("A tanner", ["leather worker", "hide worker"]),
    f("A town crier", ["public announcer", "town messenger"]),
    f("A physician", ["medieval doctor", "town healer"]),
    f("A ferryman", ["river boatman", "crossing keeper"]),
  ]),
  q("Name a monument from the ancient world.", [
    f("The Colosseum", ["Roman amphitheater", "Flavian amphitheater"]),
    f("The Parthenon", ["Greek temple", "Athenian temple"]),
    f("The Great Pyramid", ["Pyramid of Giza", "Giza pyramid"]),
    f("The Great Wall", ["Chinese wall", "China's wall"]),
    f("Stonehenge", ["stone circle", "prehistoric stones"]),
    f("Machu Picchu", ["Inca citadel", "Andean ruins"]),
    f("Petra", ["Nabataean city", "rose city"]),
    f("The Pantheon", ["Roman temple", "ancient dome"]),
    f("The Sphinx", ["Great Sphinx", "Egyptian sphinx"]),
    f("Angkor Wat", ["Khmer temple", "Angkor temple"]),
    f("The Temple of Karnak", ["Karnak temple", "Egyptian temple complex"]),
    f("The Acropolis", ["Athenian acropolis", "hilltop citadel"]),
    f("The Nazca Lines", ["Nazca geoglyphs", "desert lines"]),
    f("The Terracotta Army", ["terracotta soldiers", "clay army"]),
    f("The Lighthouse of Alexandria", ["Pharos lighthouse", "Alexandria beacon"]),
    f("The Hanging Gardens", ["Babylon gardens", "ancient gardens"]),
  ]),
  q("Name an object recovered from a shipwreck.", [
    f("A coin", ["wreck coin", "sunken coin"]),
    f("A compass", ["ship compass", "navigation compass"]),
    f("A cannon", ["ship cannon", "wreck gun"]),
    f("A bottle", ["glass bottle", "wreck bottle"]),
    f("An anchor", ["ship anchor", "sunken anchor"]),
    f("A ceramic bowl", ["wreck pottery", "ship bowl"]),
    f("A sword", ["wreck sword", "mariner's sword"]),
    f("A cargo chest", ["ship chest", "wrecked chest"]),
    f("A ship bell", ["bell from a ship", "wreck bell"]),
    f("A rope", ["ship rope", "wreck rope"]),
    f("A plate", ["ship plate", "ceramic plate"]),
    f("A navigational chart", ["sea chart", "ship map"]),
    f("A shoe", ["old shoe", "wreck footwear"]),
    f("A spoon", ["ship spoon", "wreck cutlery"]),
    f("A wooden beam", ["ship timber", "wreck wood"]),
    f("A figurehead", ["ship figurehead", "carved prow ornament"]),
  ]),
  q("Name a clue archaeologists study.", [
    f("Pottery shards", ["ceramic fragments", "broken pots"]),
    f("Burial remains", ["human remains", "ancient burials"]),
    f("Tools", ["old tools", "stone implements"]),
    f("Foundations", ["building foundations", "old footings"]),
    f("Coins", ["archaeological coins", "old currency"]),
    f("Animal bones", ["faunal remains", "ancient bones"]),
    f("Seeds", ["archaeological seeds", "ancient plant remains"]),
    f("Inscriptions", ["carved inscriptions", "written clues"]),
    f("Soil layers", ["stratigraphy", "archaeological soil"]),
    f("Charcoal", ["burned wood", "ancient charcoal"]),
    f("Jewelry", ["archaeological jewelry", "burial ornaments"]),
    f("Building stones", ["masonry blocks", "old stonework"]),
    f("Trade goods", ["imported goods", "exchange artifacts"]),
    f("Road traces", ["ancient roads", "old pathways"]),
    f("Animal tracks", ["footprints", "fossil tracks"]),
    f("Pollen", ["ancient pollen", "archaeological pollen"]),
  ]),
  q("What can cause people to migrate?", [
    f("War", ["armed conflict", "violent conflict"]),
    f("Work", ["job opportunities", "employment"]),
    f("Famine", ["food shortage", "hunger crisis"]),
    f("Drought", ["dry conditions", "water shortage"]),
    f("Persecution", ["religious persecution", "political persecution"]),
    f("Flooding", ["flood disaster", "rising water"]),
    f("Education", ["study opportunities", "school abroad"]),
    f("Family", ["joining family", "family reunion"]),
    f("Trade", ["merchant travel", "commercial migration"]),
    f("Colonization", ["settler movement", "colonial expansion"]),
    f("Natural disaster", ["earthquake", "disaster displacement"]),
    f("Political change", ["regime change", "political upheaval"]),
    f("Climate change", ["changing climate", "environmental pressure"]),
    f("Housing", ["need for housing", "housing opportunity"]),
    f("Marriage", ["marrying abroad", "marriage migration"]),
    f("Adventure", ["seeking a new life", "exploration"]),
  ]),
  q("Name a historical document.", [
    f("A constitution", ["founding constitution", "national charter"]),
    f("A treaty", ["peace treaty", "signed agreement"]),
    f("A diary", ["personal diary", "historical journal"]),
    f("A census", ["population record", "census document"]),
    f("A land deed", ["property deed", "ownership document"]),
    f("A newspaper", ["historic newspaper", "periodical"]),
    f("A birth certificate", ["birth record", "official birth document"]),
    f("A letter", ["historic letter", "personal correspondence"]),
    f("A law code", ["legal code", "written laws"]),
    f("A proclamation", ["official proclamation", "public declaration"]),
    f("A map", ["historic map", "old chart"]),
    f("A royal decree", ["king's decree", "monarch order"]),
    f("A ship log", ["captain's log", "voyage record"]),
    f("A court record", ["legal record", "trial document"]),
    f("A recipe book", ["historic cookbook", "old recipe collection"]),
    f("A manifesto", ["political manifesto", "movement document"]),
  ]),
  q("Name an object in a railway history exhibit.", [
    f("A steam engine", ["steam locomotive", "old train"]),
    f("A conductor's hat", ["railway hat", "train uniform hat"]),
    f("A ticket punch", ["ticket clipper", "rail ticket punch"]),
    f("A timetable", ["old train schedule", "rail timetable"]),
    f("A signal lamp", ["rail lamp", "train signal light"]),
    f("A railway map", ["old rail map", "train route map"]),
    f("A station clock", ["railway clock", "platform clock"]),
    f("A luggage trunk", ["travel trunk", "rail luggage"]),
    f("A rail spike", ["track spike", "railway nail"]),
    f("A dining car plate", ["train service plate", "railway crockery"]),
    f("A lantern", ["rail lantern", "train lamp"]),
    f("A whistle", ["train whistle", "conductor whistle"]),
    f("A telegraph", ["railway telegraph", "station telegraph"]),
    f("A model train", ["railway model", "miniature train"]),
    f("A sleeper berth", ["train sleeping berth", "railway bed"]),
    f("A railway uniform", ["train uniform", "rail worker clothes"]),
  ]),
  q("Name an artifact that traveled the Silk Road.", [
    f("Silk", ["silk cloth", "woven silk"]),
    f("Spices", ["trade spices", "eastern spices"]),
    f("Coins", ["trade coins", "foreign currency"]),
    f("Porcelain", ["Chinese porcelain", "fine ceramics"]),
    f("Glassware", ["glass vessels", "trade glass"]),
    f("A carpet", ["traveling carpet", "woven rug"]),
    f("Paper", ["paper sheets", "early paper"]),
    f("A saddle", ["trade saddle", "riding saddle"]),
    f("A spice jar", ["ceramic spice jar", "trade jar"]),
    f("A musical instrument", ["trade instrument", "traveling instrument"]),
    f("A manuscript", ["traveling manuscript", "silk road text"]),
    f("Jade", ["jade ornament", "jade stone"]),
    f("Tea", ["tea bricks", "trade tea"]),
    f("Perfume", ["trade perfume", "fragrant oil"]),
    f("A bronze mirror", ["ancient mirror", "bronze mirror"]),
    f("A horse", ["trade horse", "caravan horse"]),
  ]),
  q("Name a tradition inherited from earlier generations.", [
    f("A festival", ["traditional festival", "annual celebration"]),
    f("A family recipe", ["old family recipe", "inherited dish"]),
    f("A song", ["traditional song", "folk song"]),
    f("A dance", ["traditional dance", "folk dance"]),
    f("A language", ["heritage language", "ancestral tongue"]),
    f("A craft", ["traditional craft", "handmade tradition"]),
    f("A ceremony", ["traditional ceremony", "ritual"]),
    f("A story", ["family story", "old tale"]),
    f("A holiday", ["traditional holiday", "heritage holiday"]),
    f("A garment", ["traditional clothing", "heritage dress"]),
    f("A greeting", ["traditional greeting", "customary hello"]),
    f("A wedding custom", ["marriage tradition", "wedding ritual"]),
    f("A harvest ritual", ["harvest tradition", "crop celebration"]),
    f("A name", ["family name", "inherited name"]),
    f("A game", ["traditional game", "old pastime"]),
    f("A memorial", ["ancestral remembrance", "remembrance custom"]),
  ]),
  q("What might you see in a war museum?", [
    f("Uniforms", ["military uniforms", "service clothing"]),
    f("Medals", ["military medals", "service decorations"]),
    f("Weapons", ["military arms", "historic weapons"]),
    f("Photographs", ["war photos", "military photographs"]),
    f("Letters", ["soldier letters", "wartime correspondence"]),
    f("Tanks", ["battle tanks", "armored vehicles"]),
    f("A memorial wall", ["names wall", "war memorial wall"]),
    f("Maps", ["battle maps", "campaign maps"]),
    f("A trench model", ["trench exhibit", "model trench"]),
    f("A field radio", ["military radio", "wartime radio"]),
    f("A helmet", ["soldier helmet", "combat helmet"]),
    f("A ration tin", ["military rations", "soldier food tin"]),
    f("A vehicle", ["military vehicle", "war truck"]),
    f("A flag", ["military flag", "battle flag"]),
    f("A memorial book", ["roll of honor", "names book"]),
    f("A peace poster", ["wartime poster", "peace campaign poster"]),
  ]),
  q("Name a way history is preserved.", [
    f("Museums", ["history museums", "public museums"]),
    f("Archives", ["historical archives", "record archives"]),
    f("Monuments", ["historic monuments", "memorials"]),
    f("Books", ["history books", "written histories"]),
    f("Oral stories", ["oral history", "spoken stories"]),
    f("Photographs", ["historic photos", "archival pictures"]),
    f("Historic buildings", ["heritage buildings", "preserved structures"]),
    f("Artifacts", ["historic objects", "archaeological artifacts"]),
    f("Films", ["historic films", "documentary footage"]),
    f("Songs", ["traditional songs", "historical music"]),
    f("Memorial days", ["remembrance days", "commemorative holidays"]),
    f("Digital records", ["online archives", "digital history"]),
    f("Reenactments", ["historical reenactments", "living history"]),
    f("Preserved landscapes", ["historic landscapes", "heritage sites"]),
    f("Family heirlooms", ["inherited objects", "heirloom items"]),
    f("School lessons", ["history classes", "teaching history"]),
  ]),
];
