import { family as f, question as q } from "./common.mjs";

export const science = [
  q("Name something that glows in the dark.", [
    f("Stars", ["distant stars", "star light"]),
    f("A firefly", ["glow-worm", "firefly insect"]),
    f("The moon", ["moonlight", "lunar glow"]),
    f("Neon paint", ["glow paint", "fluorescent paint"]),
    f("Lava", ["molten rock", "volcanic lava"]),
    f("A glow stick", ["light stick", "chemiluminescent stick"]),
    f("Deep-sea creatures", ["bioluminescent animals", "glowing sea life"]),
    f("Aurora", ["northern lights", "polar lights"]),
    f("A campfire", ["fire", "burning wood"]),
    f("A candle", ["candle flame", "lit candle"]),
    f("A flashlight", ["torch", "hand light"]),
    f("Bioluminescent plankton", ["glowing plankton", "sea sparkle"]),
    f("A light bulb", ["lamp bulb", "electric light"]),
    f("A glow-in-the-dark toy", ["luminous toy", "glowing toy"]),
    f("A luminous watch", ["glowing watch", "lit watch face"]),
    f("A glowing mineral", ["fluorescent mineral", "glowing crystal"]),
  ]),
  q("What might you see through a microscope?", [
    f("Cells", ["living cells", "cell structures"]),
    f("Bacteria", ["bacterial cells", "microbes"]),
    f("Pollen", ["pollen grains", "flower pollen"]),
    f("A hair", ["hair strand", "single hair"]),
    f("A drop of pond water", ["pond sample", "water droplet"]),
    f("Salt crystals", ["salt grains", "crystal salt"]),
    f("Skin", ["skin cells", "human skin"]),
    f("A leaf", ["leaf cells", "plant leaf"]),
    f("A blood cell", ["red blood cell", "blood cells"]),
    f("A dust mite", ["mite", "tiny mite"]),
    f("A virus", ["viral particle", "virus particle"]),
    f("Mold", ["mould", "fungal growth"]),
    f("An amoeba", ["amoeboid cell", "single-celled amoeba"]),
    f("A muscle fiber", ["muscle cell", "muscle tissue"]),
    f("A feather", ["feather barbs", "bird feather"]),
    f("A thread", ["fiber", "fine thread"]),
  ]),
  q("Name a force you notice in daily life.", [
    f("Gravity", ["gravitational pull", "Earth's gravity"]),
    f("Friction", ["surface friction", "rubbing force"]),
    f("Wind", ["moving air", "airflow"]),
    f("Magnetism", ["magnetic force", "magnetic pull"]),
    f("Buoyancy", ["floating force", "upward force"]),
    f("Tension", ["pulling tension", "tension force"]),
    f("Air resistance", ["drag", "wind resistance"]),
    f("A push", ["pushing force", "push force"]),
    f("A pull", ["pulling force", "pull force"]),
    f("Spring force", ["elastic force", "spring tension"]),
    f("Electric force", ["electrostatic force", "charged force"]),
    f("Centripetal force", ["turning force", "inward force"]),
    f("Normal force", ["support force", "contact force"]),
    f("Torque", ["turning torque", "rotational force"]),
    f("Lift", ["aerodynamic lift", "upward lift"]),
    f("Shear", ["shearing force", "sliding force"]),
  ]),
  q("Name something that changes state.", [
    f("Water", ["liquid water", "H2O"]),
    f("Ice cream", ["frozen cream", "melting ice cream"]),
    f("Wax", ["candle wax", "melted wax"]),
    f("Chocolate", ["melted chocolate", "cocoa chocolate"]),
    f("Metal", ["molten metal", "metal material"]),
    f("Clouds", ["cloud formation", "condensation clouds"]),
    f("Dry ice", ["solid carbon dioxide", "frozen CO2"]),
    f("Butter", ["melted butter", "butter fat"]),
    f("Steam", ["boiling vapor", "hot vapor"]),
    f("Glass", ["molten glass", "glass material"]),
    f("Nitrogen", ["liquid nitrogen", "nitrogen gas"]),
    f("Alcohol", ["evaporating alcohol", "liquid ethanol"]),
    f("Sugar", ["dissolved sugar", "sugar crystals"]),
    f("Salt", ["salt solution", "salt crystals"]),
    f("Frost", ["frozen dew", "ice crystals"]),
    f("Fog", ["water droplets", "ground cloud"]),
  ]),
  q("What might you find in a coral reef?", [
    f("Parrotfish", ["reef parrotfish", "colorful parrotfish"]),
    f("Sea anemones", ["anemones", "reef anemones"]),
    f("Clownfish", ["anemonefish", "Nemo fish"]),
    f("Crabs", ["reef crabs", "small crabs"]),
    f("Sea turtles", ["marine turtles", "turtle species"]),
    f("Sponges", ["sea sponges", "reef sponges"]),
    f("Sharks", ["reef sharks", "shark species"]),
    f("Algae", ["marine algae", "seaweed"]),
    f("Coral polyps", ["coral animals", "reef polyps"]),
    f("Sea stars", ["starfish", "reef stars"]),
    f("Moray eels", ["reef eels", "moray eel"]),
    f("Jellyfish", ["jellies", "marine jellyfish"]),
    f("Clams", ["giant clams", "reef shellfish"]),
    f("Sea urchins", ["urchins", "spiny urchins"]),
    f("Sea snakes", ["reef snakes", "marine snakes"]),
    f("Plankton", ["marine plankton", "tiny drifters"]),
  ]),
  q("Name a material that conducts heat.", [
    f("Copper", ["copper metal", "copper wire"]),
    f("Aluminum", ["aluminium", "aluminum metal"]),
    f("Steel", ["steel alloy", "metal steel"]),
    f("Water", ["liquid water", "water medium"]),
    f("Silver", ["silver metal", "pure silver"]),
    f("Iron", ["iron metal", "iron material"]),
    f("Brass", ["brass alloy", "yellow brass"]),
    f("Graphite", ["carbon graphite", "pencil graphite"]),
    f("Gold", ["gold metal", "pure gold"]),
    f("Diamond", ["diamond crystal", "carbon diamond"]),
    f("Concrete", ["building concrete", "cement concrete"]),
    f("Glass", ["glass material", "window glass"]),
    f("Ceramic", ["ceramic material", "fired ceramic"]),
    f("Saltwater", ["sea water", "salty water"]),
    f("Graphene", ["graphene sheet", "carbon sheet"]),
    f("Mercury", ["liquid mercury", "quicksilver"]),
  ]),
  q("What might a field scientist carry?", [
    f("A notebook", ["field notebook", "research journal"]),
    f("Sample jars", ["specimen jars", "collection containers"]),
    f("A camera", ["field camera", "research camera"]),
    f("Binoculars", ["field glasses", "observation binoculars"]),
    f("A GPS", ["GPS receiver", "satellite navigator"]),
    f("Gloves", ["protective gloves", "field gloves"]),
    f("A first-aid kit", ["field medical kit", "emergency kit"]),
    f("A hand lens", ["magnifying glass", "field magnifier"]),
    f("A compass", ["field compass", "magnetic compass"]),
    f("Measuring tape", ["survey tape", "length tape"]),
    f("A soil probe", ["soil sampler", "ground probe"]),
    f("Test tubes", ["sample tubes", "laboratory tubes"]),
    f("A thermometer", ["field thermometer", "temperature probe"]),
    f("A backpack", ["field pack", "research bag"]),
    f("Protective glasses", ["safety goggles", "eye protection"]),
    f("A portable scale", ["field balance", "weighing scale"]),
  ]),
  q("Name something found in a garden ecosystem.", [
    f("Worms", ["earthworms", "garden worms"]),
    f("Bees", ["honeybees", "pollinating bees"]),
    f("Soil", ["garden soil", "earth"]),
    f("Mushrooms", ["fungi", "garden mushrooms"]),
    f("Birds", ["garden birds", "songbirds"]),
    f("Roots", ["plant roots", "root systems"]),
    f("Spiders", ["garden spiders", "web spiders"]),
    f("Compost", ["compost heap", "organic compost"]),
    f("Butterflies", ["garden butterflies", "winged pollinators"]),
    f("Ants", ["garden ants", "ant colony"]),
    f("Fallen leaves", ["dead leaves", "leaf litter"]),
    f("Moss", ["garden moss", "green moss"]),
    f("Snails", ["garden snails", "land snails"]),
    f("Aphids", ["plant lice", "garden aphids"]),
    f("Frogs", ["garden frogs", "small frogs"]),
    f("Seeds", ["plant seeds", "seed bank"]),
  ]),
  q("What helps protect living things from the Sun?", [
    f("Sunscreen", ["sun cream", "SPF lotion"]),
    f("Shade", ["shelter from sunlight", "a shaded place"]),
    f("Melanin", ["skin pigment", "dark pigment"]),
    f("A hat", ["sun hat", "wide-brimmed hat"]),
    f("Clouds", ["cloud cover", "overcast sky"]),
    f("Leaves", ["plant leaves", "leaf canopy"]),
    f("Sunglasses", ["sun glasses", "UV glasses"]),
    f("The ozone layer", ["ozone shield", "atmospheric ozone"]),
    f("Protective clothing", ["sun clothing", "long sleeves"]),
    f("Shelter", ["a roof", "covered shelter"]),
    f("Umbrellas", ["sun umbrellas", "handheld umbrellas"]),
    f("Reflective surfaces", ["reflective material", "light-reflecting surfaces"]),
    f("Carotenoids", ["plant pigments", "protective pigments"]),
    f("Antioxidants", ["antioxidant molecules", "cell protectors"]),
    f("A parasol", ["sun canopy", "ornamental sunshade"]),
    f("Fur", ["animal fur", "protective coat"]),
  ]),
  q("Name a source of renewable energy.", [
    f("Sunlight", ["solar energy", "the Sun"]),
    f("Wind", ["wind power", "moving air"]),
    f("Moving water", ["hydropower", "flowing water"]),
    f("Geothermal heat", ["geothermal energy", "Earth heat"]),
    f("Tides", ["tidal power", "ocean tides"]),
    f("Biomass", ["plant fuel", "organic energy"]),
    f("Ocean waves", ["wave power", "sea waves"]),
    f("Solar panels", ["photovoltaic panels", "solar cells"]),
    f("River currents", ["river power", "stream energy"]),
    f("Wood", ["firewood", "biomass wood"]),
    f("Crop waste", ["agricultural waste", "plant residue"]),
    f("Landfill gas", ["biogas", "methane gas"]),
    f("Sea currents", ["marine current power", "ocean currents"]),
    f("A wind turbine", ["windmill", "wind generator"]),
    f("A dam", ["hydroelectric dam", "power dam"]),
    f("A heat pump", ["ground-source pump", "renewable heat pump"]),
  ]),
  q("What might you measure in a laboratory?", [
    f("Temperature", ["heat level", "degrees"]),
    f("Mass", ["sample mass", "weight measurement"]),
    f("pH", ["acidity", "alkalinity"]),
    f("Time", ["duration", "elapsed time"]),
    f("Pressure", ["force per area", "pressure level"]),
    f("Volume", ["liquid volume", "sample volume"]),
    f("Light", ["light intensity", "brightness"]),
    f("Distance", ["length", "spatial distance"]),
    f("Conductivity", ["electrical conductivity", "conductance"]),
    f("Density", ["mass density", "sample density"]),
    f("Speed", ["velocity", "rate of motion"]),
    f("Wavelength", ["light wavelength", "wave length"]),
    f("Concentration", ["solution concentration", "solute level"]),
    f("Humidity", ["moisture level", "relative humidity"]),
    f("Voltage", ["electric potential", "voltage level"]),
    f("Radiation", ["radiation dose", "ionizing radiation"]),
  ]),
  q("Name something that survives an extreme environment.", [
    f("Tardigrades", ["water bears", "moss piglets"]),
    f("Cacti", ["cactus plants", "desert cacti"]),
    f("Deep-sea bacteria", ["abyssal microbes", "ocean bacteria"]),
    f("Penguins", ["polar penguins", "emperor penguins"]),
    f("Camel plants", ["desert plants", "xerophytes"]),
    f("Fungi", ["fungus", "extreme fungi"]),
    f("Brine shrimp", ["sea monkeys", "saltwater shrimp"]),
    f("Archaea", ["extreme archaea", "ancient microbes"]),
    f("Bacteria spores", ["bacterial endospores", "dormant spores"]),
    f("Lichens", ["lichen organisms", "rock lichens"]),
    f("Polar bears", ["arctic bears", "ice bears"]),
    f("Desert beetles", ["sand beetles", "dune beetles"]),
    f("Tube worms", ["vent worms", "hydrothermal worms"]),
    f("Brine flies", ["salt flies", "salt-lake flies"]),
    f("Alpine moss", ["mountain moss", "high-altitude moss"]),
    f("Extremophile algae", ["hardy algae", "extreme algae"]),
  ]),
  q("What can make the sky change color?", [
    f("Sunset", ["sunrise or sunset", "evening light"]),
    f("Clouds", ["cloud cover", "clouds in the sky"]),
    f("Dust", ["airborne dust", "dust particles"]),
    f("Aurora", ["northern lights", "polar glow"]),
    f("Smoke", ["smoke haze", "fire smoke"]),
    f("Rain", ["rain shower", "falling rain"]),
    f("A rainbow", ["rainbow arc", "colored arc"]),
    f("Pollution", ["air pollution", "urban haze"]),
    f("Volcanic ash", ["ash cloud", "eruption ash"]),
    f("Water vapor", ["atmospheric moisture", "vapor haze"]),
    f("Moonlight", ["light from the moon", "lunar light"]),
    f("Lightning", ["electrical storm", "lightning flash"]),
    f("High clouds", ["cirrus clouds", "thin clouds"]),
    f("Ocean spray", ["sea mist", "salt spray"]),
    f("The atmosphere", ["air layers", "Earth's atmosphere"]),
    f("A dust storm", ["sandstorm", "blowing dust"]),
  ]),
  q("What does the human body do in response to exercise?", [
    f("Sweat", ["perspire", "produce sweat"]),
    f("Breathe faster", ["rapid breathing", "increase breathing"]),
    f("Heart beats faster", ["faster heartbeat", "heart rate rises"]),
    f("Warm up", ["body heats up", "get warmer"]),
    f("Make more energy", ["produce energy", "generate ATP"]),
    f("Use oxygen", ["consume oxygen", "take in oxygen"]),
    f("Release adrenaline", ["produce adrenaline", "adrenaline surge"]),
    f("Drink more water", ["need hydration", "replace fluids"]),
    f("Burn calories", ["use calories", "expend energy"]),
    f("Contract muscles", ["muscles tighten", "muscle contraction"]),
    f("Dilate blood vessels", ["blood vessels widen", "vasodilation"]),
    f("Produce lactic acid", ["make lactate", "lactate buildup"]),
    f("Increase blood flow", ["blood flow rises", "circulation increases"]),
    f("Release heat", ["lose heat", "heat dissipation"]),
    f("Feel tired", ["become fatigued", "experience fatigue"]),
    f("Recover", ["repair muscles", "post-exercise recovery"]),
  ]),
  q("Name a space object people recognize.", [
    f("The Moon", ["Earth's moon", "lunar body"]),
    f("A comet", ["icy comet", "tail star"]),
    f("Mars", ["the red planet", "planet Mars"]),
    f("Saturn", ["ringed planet", "planet Saturn"]),
    f("The Sun", ["our star", "solar star"]),
    f("An asteroid", ["space rock", "minor planet"]),
    f("A black hole", ["gravitational singularity", "collapsed star"]),
    f("A galaxy", ["star galaxy", "spiral galaxy"]),
    f("Earth", ["our planet", "the world"]),
    f("Jupiter", ["giant planet", "planet Jupiter"]),
    f("Venus", ["cloudy planet", "planet Venus"]),
    f("A meteor", ["shooting star", "falling meteor"]),
    f("A nebula", ["space cloud", "stellar nebula"]),
    f("A space station", ["orbiting station", "orbital laboratory"]),
    f("A satellite", ["artificial satellite", "orbiting satellite"]),
    f("The Milky Way", ["our galaxy", "Milky Way galaxy"]),
  ]),
  q("What can make a shadow?", [
    f("A person", ["human body", "a human"]),
    f("A tree", ["tree shape", "plant shadow"]),
    f("A building", ["house shadow", "structure shadow"]),
    f("A lamp", ["light source", "desk lamp"]),
    f("A cloud", ["cloud shadow", "sky cloud"]),
    f("A mountain", ["mountain shadow", "peak shadow"]),
    f("A fence", ["fence shadow", "rail shadow"]),
    f("A bicycle", ["bike shadow", "cycle silhouette"]),
    f("A hand", ["hand shadow", "hand silhouette"]),
    f("A candle", ["candle shadow", "flame light"]),
    f("A rock", ["stone shadow", "rock silhouette"]),
    f("A bird", ["bird silhouette", "flying bird"]),
    f("A car", ["vehicle shadow", "car silhouette"]),
    f("A book", ["book shadow", "closed book"]),
    f("A statue", ["statue shadow", "sculpture silhouette"]),
    f("A flag", ["flag shadow", "flag shape"]),
  ]),
  q("Name a bit of kitchen chemistry.", [
    f("Baking soda", ["sodium bicarbonate", "bicarbonate powder"]),
    f("Vinegar", ["acetic acid", "cooking vinegar"]),
    f("Yeast", ["baking yeast", "fermentation yeast"]),
    f("Salt", ["table salt", "sodium chloride"]),
    f("Sugar", ["table sugar", "sucrose"]),
    f("Lemon juice", ["citrus acid", "lemon acid"]),
    f("Egg proteins", ["egg protein", "albumen"]),
    f("Caramel", ["caramelized sugar", "melted sugar"]),
    f("Gluten", ["wheat gluten", "bread protein"]),
    f("Oil", ["cooking oil", "vegetable oil"]),
    f("Starch", ["food starch", "corn starch"]),
    f("Citric acid", ["fruit acid", "sour acid"]),
    f("Gelatin", ["gelatine", "protein gel"]),
    f("Emulsion", ["mixed emulsion", "oil-water mixture"]),
    f("Browning", ["Maillard reaction", "food browning"]),
    f("Boiling water", ["hot water", "water at a boil"]),
  ]),
  q("Name something that floats.", [
    f("A boat", ["watercraft", "small boat"]),
    f("Wood", ["wooden block", "timber"]),
    f("Ice", ["ice cube", "frozen water"]),
    f("A leaf", ["fallen leaf", "leaf on water"]),
    f("A balloon", ["air balloon", "floating balloon"]),
    f("A cork", ["wine cork", "cork stopper"]),
    f("Oil", ["cooking oil", "oil layer"]),
    f("A life jacket", ["floatation vest", "buoyancy jacket"]),
    f("A rubber duck", ["bath duck", "rubber toy"]),
    f("A plastic bottle", ["empty bottle", "plastic container"]),
    f("A raft", ["floating raft", "wood raft"]),
    f("A bubble", ["soap bubble", "air bubble"]),
    f("A buoy", ["water buoy", "floating marker"]),
    f("A sponge", ["bath sponge", "porous sponge"]),
    f("A feather", ["bird feather", "light feather"]),
    f("A swimmer", ["person swimming", "human body in water"]),
  ]),
  q("Name evidence that the weather is changing.", [
    f("Dark clouds", ["storm clouds", "heavy clouds"]),
    f("Falling pressure", ["air pressure drop", "barometer falls"]),
    f("A rising wind", ["stronger wind", "wind picking up"]),
    f("Temperature change", ["changing temperature", "heat shift"]),
    f("Lightning", ["lightning flashes", "electrical storm"]),
    f("A weather warning", ["storm alert", "weather advisory"]),
    f("Rain starting", ["first raindrops", "rain beginning"]),
    f("A change in humidity", ["humidity shift", "moisture change"]),
    f("Moving clouds", ["cloud movement", "fast clouds"]),
    f("A rainbow", ["rainbow arc", "colored sky arc"]),
    f("Thunder", ["storm rumble", "distant thunder"]),
    f("Fog", ["mist", "ground fog"]),
    f("Hail", ["hailstones", "ice pellets"]),
    f("A changing forecast", ["updated forecast", "new weather report"]),
    f("Animal behavior", ["animals reacting", "wildlife behavior"]),
    f("A pressure front", ["weather front", "air mass boundary"]),
  ]),
  q("Name an example of symbiosis.", [
    f("Bees and flowers", ["bee pollination", "bees with blossoms"]),
    f("Clownfish and anemones", ["anemonefish partnership", "reef fish and anemone"]),
    f("Lichen", ["algae and fungus", "lichen partnership"]),
    f("Gut bacteria", ["microbiome", "intestinal microbes"]),
    f("Coral and algae", ["coral symbionts", "reef algae partnership"]),
    f("Mycorrhiza", ["fungus and roots", "root-fungus partnership"]),
    f("Oxpeckers and mammals", ["cleaner birds", "oxpecker partnership"]),
    f("Sharks and remoras", ["remora hitchhikers", "remora relationship"]),
    f("Ants and aphids", ["aphid farming", "ant-aphid relationship"]),
    f("Figs and fig wasps", ["fig pollination", "fig wasp partnership"]),
    f("Mistletoe and trees", ["tree parasite", "mistletoe host"]),
    f("Cleaner shrimp and fish", ["reef cleaners", "shrimp cleaning fish"]),
    f("Termites and microbes", ["termite gut microbes", "wood digestion partnership"]),
    f("Cattle and gut microbes", ["rumen microbes", "cow digestion symbiosis"]),
    f("Humans and dogs", ["human-dog partnership", "domestication bond"]),
    f("Plants and nitrogen bacteria", ["root nodules", "nitrogen-fixing bacteria"]),
  ]),
  q("Name an instrument used to measure time.", [
    f("A clock", ["wall clock", "time clock"]),
    f("A watch", ["wristwatch", "timepiece"]),
    f("A stopwatch", ["timer", "timing watch"]),
    f("An hourglass", ["sand timer", "sandglass"]),
    f("A sundial", ["sun clock", "shadow clock"]),
    f("A calendar", ["date calendar", "day planner"]),
    f("An atomic clock", ["precision clock", "atomic timepiece"]),
    f("A metronome", ["tempo keeper", "beat timer"]),
    f("A chronometer", ["precision timer", "marine clock"]),
    f("A water clock", ["clepsydra", "drip clock"]),
    f("A candle clock", ["candle timer", "burning clock"]),
    f("A quartz clock", ["quartz timepiece", "crystal clock"]),
    f("A pendulum clock", ["swing clock", "pendulum timepiece"]),
    f("A timer app", ["digital timer", "phone timer"]),
    f("A clock tower", ["tower clock", "public clock"]),
    f("A chronograph", ["timing instrument", "stopwatch mechanism"]),
  ]),
  q("What protects a spacecraft from radiation?", [
    f("Heat shielding", ["thermal shield", "heat shield"]),
    f("Water", ["water shielding", "water barrier"]),
    f("Aluminum", ["aluminium shielding", "metal hull"]),
    f("A magnetic field", ["magnetic shield", "magnetosphere"]),
    f("Regolith", ["lunar soil", "moon dust shielding"]),
    f("A thick hull", ["spacecraft hull", "heavy shell"]),
    f("Polyethylene", ["plastic shielding", "hydrogen-rich plastic"]),
    f("Earth's atmosphere", ["atmospheric protection", "air shield"]),
    f("Lead", ["lead shielding", "lead barrier"]),
    f("A storm shelter", ["radiation shelter", "crew shelter"]),
    f("Distance from the Sun", ["solar distance", "space distance"]),
    f("Solar panels", ["panel shielding", "protected solar cells"]),
    f("Boron material", ["boron shielding", "borated plastic"]),
    f("A plasma shield", ["plasma barrier", "charged-particle shield"]),
    f("A safe room", ["shielded compartment", "protected cabin"]),
    f("Mission timing", ["radiation avoidance", "timed mission"]),
  ]),
  q("Name one of the body's senses.", [
    f("Sight", ["vision", "seeing"]),
    f("Hearing", ["audition", "listening"]),
    f("Smell", ["olfaction", "scent detection"]),
    f("Taste", ["gustation", "flavor sense"]),
    f("Touch", ["feeling", "tactile sense"]),
    f("Balance", ["equilibrium", "body balance"]),
    f("Temperature", ["heat sensing", "thermal sense"]),
    f("Pain", ["nociception", "pain detection"]),
    f("Pressure", ["pressure sense", "body pressure"]),
    f("Proprioception", ["body position", "position sense"]),
    f("Vibration", ["vibration sense", "feeling vibrations"]),
    f("Hunger", ["appetite", "hunger signal"]),
    f("Thirst", ["need for water", "thirst signal"]),
    f("Stretch", ["muscle stretch", "stretch sense"]),
    f("Motion", ["movement sense", "sensing motion"]),
    f("Time perception", ["sense of time", "temporal sense"]),
  ]),
  q("Name a material that is transparent.", [
    f("Glass", ["window glass", "clear glass"]),
    f("Water", ["clear water", "liquid water"]),
    f("Air", ["the atmosphere", "clear air"]),
    f("Acrylic", ["clear acrylic", "plastic glass"]),
    f("Quartz", ["clear quartz", "quartz crystal"]),
    f("Cellophane", ["clear wrap", "transparent film"]),
    f("Ice", ["clear ice", "ice block"]),
    f("Diamond", ["clear diamond", "diamond crystal"]),
    f("Polycarbonate", ["clear polycarbonate", "transparent plastic"]),
    f("Resin", ["clear resin", "casting resin"]),
    f("Oil", ["clear oil", "liquid oil"]),
    f("Silicone", ["clear silicone", "transparent silicone"]),
    f("Nylon", ["clear nylon", "transparent nylon"]),
    f("Lucite", ["clear lucite", "plastic lucite"]),
    f("A lens", ["optical lens", "clear lens"]),
    f("A prism", ["glass prism", "optical prism"]),
  ]),
  q("Name a process that recycles carbon.", [
    f("Photosynthesis", ["plant photosynthesis", "carbon fixation"]),
    f("Respiration", ["cellular respiration", "breathing metabolism"]),
    f("Decomposition", ["decay", "organic decomposition"]),
    f("Combustion", ["burning", "fuel combustion"]),
    f("Ocean absorption", ["carbon uptake", "sea carbon sink"]),
    f("Carbon burial", ["sediment burial", "geological carbon storage"]),
    f("Volcanic release", ["volcanic carbon", "volcano emissions"]),
    f("Weathering", ["rock weathering", "chemical weathering"]),
    f("Fossilization", ["fossil formation", "buried organic matter"]),
    f("Methane oxidation", ["methane breakdown", "methane cycling"]),
    f("Soil respiration", ["soil carbon release", "ground respiration"]),
    f("Peat formation", ["peat storage", "bog carbon storage"]),
    f("Carbon capture", ["capturing CO2", "carbon sequestration"]),
    f("Plant growth", ["biomass production", "growing plants"]),
    f("Wildfire", ["forest fire", "vegetation burning"]),
    f("Sedimentation", ["sediment settling", "carbon sediments"]),
  ]),
  q("Name something that stores energy.", [
    f("A battery", ["chemical battery", "electric cell"]),
    f("Food", ["stored food energy", "calories"]),
    f("Fuel", ["chemical fuel", "energy fuel"]),
    f("A spring", ["coiled spring", "elastic spring"]),
    f("A reservoir", ["stored water", "dam reservoir"]),
    f("A flywheel", ["rotating wheel", "mechanical storage"]),
    f("A capacitor", ["electric capacitor", "charge storage"]),
    f("Wood", ["firewood", "stored biomass"]),
    f("Fat", ["body fat", "stored fat"]),
    f("A raised weight", ["gravitational energy", "elevated mass"]),
    f("Hydrogen", ["hydrogen fuel", "stored hydrogen"]),
    f("A compressed gas", ["pressurized gas", "gas storage"]),
    f("Coal", ["coal fuel", "fossil energy"]),
    f("A thermal mass", ["stored heat", "heat storage"]),
    f("Starch", ["plant starch", "stored carbohydrate"]),
    f("A solar battery", ["home battery", "solar storage"]),
  ]),
  q("Name something visible in the night sky.", [
    f("Stars", ["night stars", "star field"]),
    f("The Moon", ["moon", "lunar disk"]),
    f("Planets", ["visible planets", "wandering stars"]),
    f("A satellite", ["orbiting satellite", "space satellite"]),
    f("A meteor", ["shooting star", "falling star"]),
    f("A comet", ["comet tail", "icy visitor"]),
    f("The Milky Way", ["galaxy band", "our galaxy"]),
    f("An aurora", ["northern lights", "polar lights"]),
    f("A constellation", ["star pattern", "group of stars"]),
    f("The International Space Station", ["ISS", "space station"]),
    f("Airplanes", ["aircraft lights", "plane in the sky"]),
    f("Clouds", ["night clouds", "cloud cover"]),
    f("Lightning", ["storm flashes", "distant lightning"]),
    f("A rocket launch", ["launch plume", "space launch"]),
    f("Earthshine", ["moon earthshine", "lunar earthlight"]),
    f("A star cluster", ["open cluster", "globular cluster"]),
  ]),
  q("Name an adaptation that helps a desert organism.", [
    f("Thick skin", ["tough skin", "water-saving skin"]),
    f("Spines", ["cactus spines", "protective spines"]),
    f("Nocturnal activity", ["being active at night", "night activity"]),
    f("Water storage", ["storing water", "water reserve"]),
    f("Large ears", ["big ears", "heat-dumping ears"]),
    f("Deep roots", ["long roots", "deep root systems"]),
    f("Camouflage", ["desert camouflage", "sand coloring"]),
    f("Burrowing", ["living underground", "digging burrows"]),
    f("Waxy leaves", ["coated leaves", "leaf wax"]),
    f("Light fur", ["pale fur", "sand-colored fur"]),
    f("Concentrated urine", ["water-saving kidneys", "concentrated waste"]),
    f("Hump fat", ["camel hump", "fat storage hump"]),
    f("Wide feet", ["sand feet", "broad paws"]),
    f("Salt glands", ["salt excretion", "salt glands"]),
    f("Dormancy", ["aestivation", "dry-season dormancy"]),
    f("Reflective scales", ["shiny scales", "light-reflecting scales"]),
  ]),
  q("Name something made by fermentation.", [
    f("Bread", ["yeast bread", "fermented dough"]),
    f("Yogurt", ["yoghurt", "cultured milk"]),
    f("Beer", ["brewed beer", "fermented drink"]),
    f("Wine", ["fermented grape juice", "grape wine"]),
    f("Cheese", ["cultured cheese", "aged cheese"]),
    f("Kimchi", ["spicy fermented cabbage", "Korean pickle"]),
    f("Sauerkraut", ["fermented cabbage", "sour cabbage"]),
    f("Kombucha", ["fermented tea", "tea culture drink"]),
    f("Miso", ["fermented soybean paste", "soybean miso"]),
    f("Soy sauce", ["fermented soy sauce", "shoyu"]),
    f("Vinegar", ["acetic fermentation", "sour vinegar"]),
    f("Pickles", ["fermented pickles", "brined vegetables"]),
    f("Kefir", ["cultured kefir", "fermented milk drink"]),
    f("Cider", ["fermented apple juice", "apple cider"]),
    f("Tempeh", ["fermented soy cake", "soy tempeh"]),
    f("Sourdough", ["sourdough bread", "starter bread"]),
  ]),
  q("Name a way plants disperse their seeds.", [
    f("Wind", ["wind dispersal", "airborne seeds"]),
    f("Water", ["water dispersal", "floating seeds"]),
    f("Animals", ["animal dispersal", "animals carry seeds"]),
    f("Exploding pods", ["bursting seed pods", "pod explosion"]),
    f("Gravity", ["falling seeds", "gravity dispersal"]),
    f("Sticky fruits", ["seeds on fur", "adhesive seeds"]),
    f("Edible fruit", ["fruit-eating animals", "fruit seed dispersal"]),
    f("Burrs", ["burr seeds", "hooked seeds"]),
    f("Awns", ["barbed awns", "grass awns"]),
    f("Animal droppings", ["seed-filled droppings", "dung dispersal"]),
    f("Squirrels", ["buried nuts", "squirrel seed carrying"]),
    f("Birds", ["bird dispersal", "birds spread seeds"]),
    f("Ants", ["ant seed dispersal", "ants carry seeds"]),
    f("Tides", ["tidal dispersal", "sea-drift seeds"]),
    f("Fire", ["fire-triggered seeds", "heat dispersal"]),
    f("Human planting", ["people spread seeds", "cultivation"]),
  ]),
];
